# Generated by Django 6.0.3 on 2026-04-27 02:37

import common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted (null if active)', null=True)),
                ('email', common.fields.LowercaseEmailField(db_index=True, help_text='Registrant email (canonical, lowercase)', max_length=254)),
                ('full_name', models.CharField(help_text='Full name as entered at registration', max_length=255)),
                ('professional_title', models.CharField(blank=True, help_text='Professional title', max_length=255)),
                ('organization_name', models.CharField(blank=True, help_text='Organization/company', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled')], db_index=True, default='confirmed', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('na', 'N/A')], db_index=True, default='na', max_length=20)),
                ('payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, help_text='Stripe Checkout Session id (cs_...) that fulfilled this registration', max_length=255, null=True, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax reported by Stripe Checkout (automatic_tax)', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount charged (ticket + tax)', max_digits=10)),
                ('source', models.CharField(choices=[('self', 'Self Registration'), ('invite', 'Invitation Link'), ('import', 'CSV Import'), ('manual', 'Manual Entry'), ('api', 'API')], default='self', help_text='How this registration was created', max_length=20)),
                ('waitlist_position', models.PositiveIntegerField(blank=True, help_text='Position in waitlist (1 = first)', null=True)),
                ('promoted_from_waitlist_at', models.DateTimeField(blank=True, help_text='When promoted from waitlist to confirmed', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('attended', models.BooleanField(default=False, help_text='Whether attendee joined the event')),
                ('check_in_time', models.DateTimeField(blank=True, help_text='When attendee was checked in', null=True)),
                ('first_join_at', models.DateTimeField(blank=True, help_text='First time attendee joined', null=True)),
                ('last_leave_at', models.DateTimeField(blank=True, help_text='Last time attendee left', null=True)),
                ('total_attendance_minutes', models.PositiveIntegerField(default=0, help_text='Total minutes attended (sum of all sessions)')),
                ('attendance_eligible', models.BooleanField(default=False, help_text='Met minimum attendance threshold')),
                ('attendance_override', models.BooleanField(default=False, help_text='Attendance manually overridden by organizer')),
                ('attendance_override_reason', models.TextField(blank=True, help_text='Reason for override')),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_issued_at', models.DateTimeField(blank=True, null=True)),
                ('allow_public_verification', models.BooleanField(default=True, help_text='Allow certificate to be publicly verified')),
                ('attendance_override_by', models.ForeignKey(blank=True, help_text='Who set the override', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overrides', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('purchase', models.ForeignKey(blank=True, help_text='Unified receipt row (CoursePurchase). Set on fulfilment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='billing.coursepurchase')),
                ('registered_by', models.ForeignKey(blank=True, help_text='User who created this registration (organizer for manual adds)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Linked user account (null for guests)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
                'db_table': 'registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('value', models.TextField(blank=True, help_text='Response value (JSON for multi-select)')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='events.eventcustomfield')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_responses', to='registrations.registration')),
            ],
            options={
                'verbose_name': 'Custom Field Response',
                'verbose_name_plural': 'Custom Field Responses',
                'db_table': 'custom_field_responses',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('participant_id', models.CharField(blank=True, help_text='Provider participant ID (unique per meeting session)', max_length=100)),
                ('external_user_id', models.CharField(blank=True, help_text='External user id (for registered provider users)', max_length=100)),
                ('participant_email', common.fields.LowercaseEmailField(blank=True, db_index=True, help_text='Email from the video provider (for matching)', max_length=254)),
                ('participant_name', models.CharField(blank=True, help_text='Display name in the meeting', max_length=255)),
                ('join_method', models.CharField(blank=True, help_text='How attendee joined (web, app, phone)', max_length=50)),
                ('device_type', models.CharField(blank=True, help_text='Device type (Windows, Mac, iOS, Android)', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address (if available)', null=True)),
                ('location', models.CharField(blank=True, help_text='GeoIP location', max_length=100)),
                ('join_time', models.DateTimeField(db_index=True, help_text='When participant joined')),
                ('leave_time', models.DateTimeField(blank=True, help_text='When participant left (null if still in meeting)', null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Duration in minutes')),
                ('is_matched', models.BooleanField(db_index=True, default=False, help_text='Successfully matched to a registration')),
                ('matched_at', models.DateTimeField(blank=True, help_text='When match was made', null=True)),
                ('matched_manually', models.BooleanField(default=False, help_text='Match was done manually by organizer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='events.event')),
                ('matched_by', models.ForeignKey(blank=True, help_text='Who performed manual match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_matches', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(blank=True, help_text='Matched registration (null if unmatched)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='registrations.registration')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance_records',
                'ordering': ['join_time'],
            },
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event', 'status'], name='registratio_event_i_6c7d81_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['email'], name='registratio_email_43b439_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['user'], name='registratio_user_id_6e12f5_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['uuid'], name='registratio_uuid_93f26b_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event', 'attendance_eligible'], name='registratio_event_i_43b1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['user', 'status'], name='registratio_user_id_d8db7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('event', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='customfieldresponse',
            unique_together={('registration', 'field')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['event', 'registration'], name='attendance__event_i_05e0d9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['event', 'is_matched'], name='attendance__event_i_4d1371_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['participant_email'], name='attendance__partici_51bcb4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['participant_id'], name='attendance__partici_33bfe3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['join_time'], name='attendance__join_ti_173a90_idx'),
        ),
    ]
