# Generated by Django 6.0 on 2025-12-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='check_in_time',
            field=models.DateTimeField(blank=True, help_text='When attendee was checked in', null=True),
        ),
    ]
