# Generated by Django 6.0 on 2026-01-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='zoom_add_attempt_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of attempts to add registrant to Zoom'),
        ),
        migrations.AddField(
            model_name='registration',
            name='zoom_add_error',
            field=models.TextField(blank=True, help_text='Last error when adding to Zoom'),
        ),
    ]
