# Generated by Django 6.0.3 on 2026-04-28 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='comped_by',
            field=models.ForeignKey(blank=True, help_text='Organizer who granted the comp seat (when was_comped=True)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_comped', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='was_comped',
            field=models.BooleanField(default=False, help_text='True iff this registration was granted as a comp seat (no payment required)'),
        ),
    ]
