# Generated by Django 6.0 on 2026-01-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='zoom_registrant_id',
            field=models.CharField(blank=True, help_text='Zoom registrant ID from Zoom API', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='zoom_registrant_join_url',
            field=models.URLField(blank=True, help_text='Unique Zoom join URL for this registrant', max_length=2000),
        ),
    ]
