# Generated by Django 6.0 on 2025-12-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('paid', 'Paid'),
                    ('failed', 'Failed'),
                    ('refunded', 'Refunded'),
                    ('na', 'N/A'),
                ],
                db_index=True,
                default='na',
                max_length=20,
            ),
        ),
    ]
