# Generated by Django 6.0 on 2026-01-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_zoom_registrant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending Payment'),
                    ('confirmed', 'Confirmed'),
                    ('waitlisted', 'Waitlisted'),
                    ('cancelled', 'Cancelled'),
                ],
                db_index=True,
                default='confirmed',
                max_length=20,
            ),
        ),
    ]
