# Generated by Django 6.0.3 on 2026-04-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_rename_attendance_zoom_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='stripe_transfer_id',
        ),
    ]
