# Generated by Django 6.0.3 on 2026-04-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_drop_stripe_transfer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='billing_postal_code',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='platform_fee_amount',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='processing_fee_amount',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='service_fee_amount',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='stripe_tax_calculation_id',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='stripe_tax_transaction_id',
        ),
        migrations.AddField(
            model_name='registration',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Checkout Session id (cs_...) that fulfilled this registration', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax reported by Stripe Checkout (automatic_tax)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount charged (ticket + tax)', max_digits=10),
        ),
    ]
