# Generated by Django 6.0 on 2026-01-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_add_pending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='platform_fee_amount',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Platform service fee charged to attendee',
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name='registration',
            name='total_amount',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Total amount charged (ticket + platform fee)',
                max_digits=10,
            ),
        ),
    ]
