# Generated by Django 6.0 on 2026-01-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_add_fee_and_tax_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='total_amount',
            field=models.DecimalField(
                decimal_places=2, default=0, help_text='Total amount charged (ticket + fees + tax)', max_digits=10
            ),
        ),
    ]
