# Generated by Django 6.0 on 2026-01-16 23:51

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import badges.models
import common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0002_initial'),
        ('organizations', '0001_initial'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, db_index=True, help_text='When this record was soft-deleted (null if active)', null=True
                    ),
                ),
                ('name', models.CharField(help_text='Template name', max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                (
                    'start_image',
                    models.ImageField(help_text='Base image for the badge (PNG/JPG)', upload_to='badges/templates/'),
                ),
                ('width_px', models.PositiveIntegerField(default=500, help_text='Image width in pixels')),
                ('height_px', models.PositiveIntegerField(default=500, help_text='Image height in pixels')),
                (
                    'field_positions',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Positions and styling for dynamic fields (x, y, font, color)',
                        validators=[common.validators.validate_field_positions_schema],
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                ('is_shared', models.BooleanField(default=False)),
                (
                    'organization',
                    models.ForeignKey(
                        blank=True,
                        help_text='Organization that owns this template',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='badge_templates',
                        to='organizations.organization',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        help_text='Organizer who owns this template',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='badge_templates',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'badge_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssuedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, db_index=True, help_text='When this record was soft-deleted (null if active)', null=True
                    ),
                ),
                (
                    'verification_code',
                    models.CharField(
                        db_index=True, default=badges.models.generate_verification_code, max_length=30, unique=True
                    ),
                ),
                ('short_code', models.CharField(default=badges.models.generate_short_code, max_length=10, unique=True)),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20
                    ),
                ),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_url', models.URLField(blank=True, help_text='URL to generated badge image')),
                ('image_generated_at', models.DateTimeField(blank=True, null=True)),
                ('badge_data', models.JSONField(default=dict, help_text='Snapshot of data at issuance')),
                (
                    'course_enrollment',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='badges',
                        to='learning.courseenrollment',
                    ),
                ),
                (
                    'issued_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='badges_issued', to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'recipient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='earned_badges', to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'registration',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='badges',
                        to='registrations.registration',
                    ),
                ),
                (
                    'template',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='issued_badges', to='badges.badgetemplate'
                    ),
                ),
            ],
            options={
                'db_table': 'issued_badges',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='badgetemplate',
            index=models.Index(fields=['owner'], name='badge_templ_owner_i_213b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='badgetemplate',
            index=models.Index(fields=['organization'], name='badge_templ_organiz_569fea_idx'),
        ),
        migrations.AddIndex(
            model_name='issuedbadge',
            index=models.Index(fields=['recipient'], name='issued_badg_recipie_8f3a24_idx'),
        ),
        migrations.AddIndex(
            model_name='issuedbadge',
            index=models.Index(fields=['template'], name='issued_badg_templat_db7e53_idx'),
        ),
        migrations.AddIndex(
            model_name='issuedbadge',
            index=models.Index(fields=['short_code'], name='issued_badg_short_c_3a457d_idx'),
        ),
    ]
