# Generated by Django 6.0 on 2026-01-19 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badges', '0001_initial'),
        ('learning', '0001_initial'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbadge',
            name='course_enrollment',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='badges',
                to='learning.courseenrollment',
            ),
        ),
        migrations.AddField(
            model_name='issuedbadge',
            name='issued_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='badges_issued', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='issuedbadge',
            name='recipient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='earned_badges', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='issuedbadge',
            name='registration',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='badges',
                to='registrations.registration',
            ),
        ),
        migrations.AddField(
            model_name='issuedbadge',
            name='template',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='issued_badges', to='badges.badgetemplate'
            ),
        ),
        migrations.AddField(
            model_name='badgestatushistory',
            name='badge',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='badges.issuedbadge'
            ),
        ),
        migrations.AddIndex(
            model_name='badgetemplate',
            index=models.Index(fields=['owner'], name='badge_templ_owner_i_213b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='issuedbadge',
            index=models.Index(fields=['recipient'], name='issued_badg_recipie_8f3a24_idx'),
        ),
        migrations.AddIndex(
            model_name='issuedbadge',
            index=models.Index(fields=['template'], name='issued_badg_templat_db7e53_idx'),
        ),
        migrations.AddIndex(
            model_name='issuedbadge',
            index=models.Index(fields=['short_code'], name='issued_badg_short_c_3a457d_idx'),
        ),
    ]
