# Generated by Django 6.0 on 2025-12-13 16:20

import common.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("certificates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public identifier for external use",
                        unique=True,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this record was soft-deleted (null if active)",
                        null=True,
                    ),
                ),
                ("title", models.CharField(help_text="Event title", max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=250, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Event description (supports markdown)",
                        max_length=10000,
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description for listings",
                        max_length=500,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("webinar", "Webinar"),
                            ("workshop", "Workshop"),
                            ("conference", "Conference"),
                            ("training", "Training Session"),
                            ("lecture", "Lecture"),
                            ("other", "Other"),
                        ],
                        default="webinar",
                        help_text="Type of event",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("live", "Live"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", help_text="Event timezone", max_length=50
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        db_index=True, help_text="Scheduled start time"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Duration in minutes (15-480)",
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(480),
                        ],
                    ),
                ),
                (
                    "actual_start_at",
                    models.DateTimeField(
                        blank=True, help_text="When event actually started", null=True
                    ),
                ),
                (
                    "actual_end_at",
                    models.DateTimeField(
                        blank=True, help_text="When event actually ended", null=True
                    ),
                ),
                (
                    "registration_enabled",
                    models.BooleanField(
                        default=True, help_text="Accept new registrations"
                    ),
                ),
                (
                    "max_attendees",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum attendees (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "registration_deadline",
                    models.DateTimeField(
                        blank=True, help_text="Registration cutoff time", null=True
                    ),
                ),
                (
                    "waitlist_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable waitlist when full"
                    ),
                ),
                (
                    "waitlist_max",
                    models.PositiveIntegerField(
                        blank=True, help_text="Max waitlist size", null=True
                    ),
                ),
                (
                    "allow_guest_registration",
                    models.BooleanField(
                        default=True, help_text="Allow registration without account"
                    ),
                ),
                (
                    "zoom_meeting_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Zoom meeting ID",
                        max_length=20,
                    ),
                ),
                (
                    "zoom_meeting_uuid",
                    models.CharField(
                        blank=True, help_text="Zoom meeting UUID", max_length=100
                    ),
                ),
                (
                    "zoom_join_url",
                    models.URLField(
                        blank=True, help_text="Zoom join URL for attendees"
                    ),
                ),
                (
                    "zoom_start_url",
                    models.URLField(
                        blank=True, help_text="Zoom start URL for host", max_length=2000
                    ),
                ),
                (
                    "zoom_password",
                    models.CharField(
                        blank=True, help_text="Zoom meeting password", max_length=50
                    ),
                ),
                (
                    "zoom_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Zoom meeting settings",
                        validators=[common.validators.validate_zoom_settings_schema],
                    ),
                ),
                (
                    "cpd_enabled",
                    models.BooleanField(
                        default=True, help_text="Event offers CPD credits"
                    ),
                ),
                (
                    "cpd_credit_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of CPD credits (e.g., CME, CPE)",
                        max_length=50,
                    ),
                ),
                (
                    "cpd_credit_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Number of CPD credits",
                        max_digits=5,
                    ),
                ),
                (
                    "cpd_accreditation_note",
                    models.TextField(
                        blank=True, help_text="Accreditation details", max_length=1000
                    ),
                ),
                (
                    "minimum_attendance_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum minutes for certificate eligibility",
                    ),
                ),
                (
                    "minimum_attendance_percent",
                    models.PositiveIntegerField(
                        default=80,
                        help_text="Minimum % attendance for certificate",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "certificates_enabled",
                    models.BooleanField(
                        default=True, help_text="Issue certificates for this event"
                    ),
                ),
                (
                    "auto_issue_certificates",
                    models.BooleanField(
                        default=False, help_text="Auto-issue when event completes"
                    ),
                ),
                (
                    "cover_image_url",
                    models.URLField(blank=True, help_text="Cover image URL"),
                ),
                (
                    "recording_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable cloud recording"
                    ),
                ),
                (
                    "recording_auto_publish",
                    models.BooleanField(
                        default=False, help_text="Auto-publish recording when available"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Visible in public listings"
                    ),
                ),
                (
                    "registration_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Confirmed registrations"
                    ),
                ),
                (
                    "waitlist_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Waitlisted registrations"
                    ),
                ),
                (
                    "attendance_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Attendees who joined"
                    ),
                ),
                (
                    "certificate_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Certificates issued"
                    ),
                ),
                (
                    "certificate_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template for certificates",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="certificates.certificatetemplate",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Organizer who owns this event",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "events",
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="EventCustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public identifier for external use",
                        unique=True,
                    ),
                ),
                ("label", models.CharField(help_text="Field label", max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Single Line Text"),
                            ("textarea", "Multi-line Text"),
                            ("select", "Dropdown"),
                            ("multiselect", "Multi-select"),
                            ("checkbox", "Checkbox"),
                            ("radio", "Radio Buttons"),
                            ("date", "Date"),
                            ("number", "Number"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False, help_text="Is this field required"
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True, help_text="Placeholder text", max_length=200
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True,
                        help_text="Help text shown below field",
                        max_length=500,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Options for select field (list of strings)",
                    ),
                ),
                ("min_value", models.IntegerField(blank=True, null=True)),
                ("max_value", models.IntegerField(blank=True, null=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (0 = first)"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Custom Field",
                "verbose_name_plural": "Event Custom Fields",
                "db_table": "event_custom_fields",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="EventStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public identifier for external use",
                        unique=True,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("reason", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Status History",
                "verbose_name_plural": "Event Status Histories",
                "db_table": "event_status_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["owner", "status"], name="events_owner_i_4a461e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "-starts_at"], name="events_status_3c2568_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["starts_at"], name="events_starts__f39f74_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["uuid"], name="events_uuid_5c78dd_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["slug"], name="events_slug_930801_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["zoom_meeting_id"], name="events_zoom_me_ba64fe_idx"
            ),
        ),
    ]
