# Generated by Django 6.0 on 2026-01-19 06:47

import common.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badges', '0001_initial'),
        ('certificates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('is_eligible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Session Attendance',
                'verbose_name_plural': 'Session Attendance',
                'db_table': 'session_attendance',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('name', models.CharField(help_text='Speaker full name', max_length=200)),
                ('bio', models.TextField(help_text='Speaker biography')),
                ('qualifications', models.TextField(help_text='Professional qualifications/credentials')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/photos/')),
                ('email', models.EmailField(blank=True, help_text='Contact email (internal use)', max_length=254)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this speaker profile is active')),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
                'db_table': 'speakers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, db_index=True, help_text='When this record was soft-deleted (null if active)', null=True
                    ),
                ),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=250, unique=True)),
                (
                    'description',
                    models.TextField(blank=True, help_text='Event description (supports markdown)', max_length=10000),
                ),
                ('short_description', models.CharField(blank=True, help_text='Brief description for listings', max_length=500)),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('webinar', 'Webinar'),
                            ('workshop', 'Workshop'),
                            ('training', 'Training Session'),
                            ('lecture', 'Lecture'),
                            ('other', 'Other'),
                        ],
                        default='webinar',
                        help_text='Type of event',
                        max_length=20,
                    ),
                ),
                (
                    'format',
                    models.CharField(
                        choices=[('online', 'Online'), ('in-person', 'In Person'), ('hybrid', 'Hybrid')],
                        default='online',
                        help_text='Event format',
                        max_length=20,
                    ),
                ),
                ('is_multi_session', models.BooleanField(default=False, help_text='Is this a multi-session event?')),
                (
                    'learning_objectives',
                    models.JSONField(blank=True, default=list, help_text='List of learning objectives (strings)'),
                ),
                (
                    'multi_session_completion_criteria',
                    models.CharField(
                        choices=[
                            ('all_sessions', 'All Sessions'),
                            ('percentage_of_sessions', 'Percentage of Sessions'),
                            ('min_sessions_count', 'Minimum Number of Sessions'),
                            ('total_minutes', 'Total Attendance Minutes (across all sessions)'),
                        ],
                        default='total_minutes',
                        help_text='Criteria for marking a multi-session event as completed for certificate eligibility',
                        max_length=50,
                    ),
                ),
                (
                    'multi_session_completion_value',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='Value for multi-session completion criteria (e.g., 80 for percentage, 3 for min sessions)',
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('published', 'Published'),
                            ('live', 'Live'),
                            ('completed', 'Completed'),
                            ('closed', 'Closed'),
                            ('cancelled', 'Cancelled'),
                        ],
                        db_index=True,
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('timezone', models.CharField(default='UTC', help_text='Event timezone', max_length=50)),
                ('starts_at', models.DateTimeField(db_index=True, help_text='Scheduled start time')),
                (
                    'duration_minutes',
                    models.PositiveIntegerField(
                        default=60,
                        help_text='Duration in minutes (15-480)',
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(480),
                        ],
                    ),
                ),
                ('actual_start_at', models.DateTimeField(blank=True, help_text='When event actually started', null=True)),
                ('actual_end_at', models.DateTimeField(blank=True, help_text='When event actually ended', null=True)),
                (
                    'currency',
                    models.CharField(
                        choices=[
                            ('USD', 'US Dollar ($)'),
                            ('CAD', 'Canadian Dollar (CA$)'),
                            ('EUR', 'Euro (€)'),
                            ('GBP', 'British Pound (£)'),
                            ('AUD', 'Australian Dollar (A$)'),
                            ('JPY', 'Japanese Yen (¥)'),
                            ('INR', 'Indian Rupee (₹)'),
                        ],
                        default='USD',
                        help_text='Currency code (ISO 4217)',
                        max_length=3,
                    ),
                ),
                (
                    'price',
                    models.DecimalField(decimal_places=2, default=0.0, help_text='Ticket price (0.00 for free)', max_digits=10),
                ),
                ('registration_enabled', models.BooleanField(default=True, help_text='Accept new registrations')),
                (
                    'max_attendees',
                    models.PositiveIntegerField(blank=True, help_text='Maximum attendees (null = unlimited)', null=True),
                ),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='Registration cutoff time', null=True)),
                ('registration_opens_at', models.DateTimeField(blank=True, help_text='When registration opens', null=True)),
                ('registration_closes_at', models.DateTimeField(blank=True, help_text='When registration closes', null=True)),
                ('waitlist_enabled', models.BooleanField(default=False, help_text='Enable waitlist when full')),
                ('waitlist_max', models.PositiveIntegerField(blank=True, help_text='Max waitlist size', null=True)),
                (
                    'waitlist_auto_promote',
                    models.BooleanField(default=False, help_text='Automatically promote from waitlist when spots open'),
                ),
                ('allow_guest_registration', models.BooleanField(default=True, help_text='Allow registration without account')),
                ('zoom_meeting_id', models.CharField(blank=True, db_index=True, help_text='Zoom meeting ID', max_length=20)),
                ('zoom_meeting_uuid', models.CharField(blank=True, help_text='Zoom meeting UUID', max_length=100)),
                ('zoom_join_url', models.URLField(blank=True, help_text='Zoom join URL for attendees')),
                ('zoom_start_url', models.URLField(blank=True, help_text='Zoom start URL for host', max_length=2000)),
                ('zoom_password', models.CharField(blank=True, help_text='Zoom meeting password', max_length=50)),
                (
                    'zoom_settings',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Zoom meeting settings',
                        validators=[common.validators.validate_zoom_settings_schema],
                    ),
                ),
                ('zoom_error', models.TextField(blank=True, help_text='Last Zoom integration error message')),
                ('zoom_error_at', models.DateTimeField(blank=True, help_text='When last Zoom error occurred', null=True)),
                ('cpd_enabled', models.BooleanField(default=True, help_text='Event offers CPD credits')),
                (
                    'cpd_credit_type',
                    models.CharField(blank=True, help_text='Type of CPD credits (e.g., CME, CPE)', max_length=50),
                ),
                (
                    'cpd_credit_value',
                    models.DecimalField(decimal_places=2, default=0, help_text='Number of CPD credits', max_digits=5),
                ),
                ('cpd_accreditation_note', models.TextField(blank=True, help_text='Accreditation details', max_length=1000)),
                (
                    'minimum_attendance_minutes',
                    models.PositiveIntegerField(default=0, help_text='Minimum minutes for certificate eligibility'),
                ),
                (
                    'minimum_attendance_percent',
                    models.PositiveIntegerField(
                        default=80,
                        help_text='Minimum % attendance for certificate',
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ('certificates_enabled', models.BooleanField(default=True, help_text='Issue certificates for this event')),
                ('auto_issue_certificates', models.BooleanField(default=False, help_text='Auto-issue when event completes')),
                (
                    'require_feedback_for_certificate',
                    models.BooleanField(
                        default=False, help_text='Require attendees to submit feedback before downloading/accessing certificate'
                    ),
                ),
                ('badges_enabled', models.BooleanField(default=False, help_text='Issue badges for this event')),
                ('auto_issue_badges', models.BooleanField(default=False, help_text='Auto-issue badges when event completes')),
                ('cover_image_url', models.URLField(blank=True, help_text='Cover image URL')),
                (
                    'featured_image',
                    models.ImageField(
                        blank=True, help_text='Featured image upload', null=True, upload_to='events/featured_images/'
                    ),
                ),
                ('location', models.CharField(blank=True, help_text='Venue address or location description', max_length=500)),
                ('recording_enabled', models.BooleanField(default=False, help_text='Enable cloud recording')),
                (
                    'recording_auto_publish',
                    models.BooleanField(default=False, help_text='Auto-publish recording when available'),
                ),
                ('is_public', models.BooleanField(default=True, help_text='Visible in public listings')),
                ('registration_count', models.PositiveIntegerField(default=0, help_text='Confirmed registrations')),
                ('waitlist_count', models.PositiveIntegerField(default=0, help_text='Waitlisted registrations')),
                ('attendance_count', models.PositiveIntegerField(default=0, help_text='Attendees who joined')),
                ('certificate_count', models.PositiveIntegerField(default=0, help_text='Certificates issued')),
                (
                    'badge_template',
                    models.ForeignKey(
                        blank=True,
                        help_text='Template for badges',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='events',
                        to='badges.badgetemplate',
                    ),
                ),
                (
                    'certificate_template',
                    models.ForeignKey(
                        blank=True,
                        help_text='Template for certificates',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='events',
                        to='certificates.certificatetemplate',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        help_text='Organizer who owns this event',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='events',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EventCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('label', models.CharField(help_text='Field label', max_length=200)),
                (
                    'field_type',
                    models.CharField(
                        choices=[
                            ('text', 'Single Line Text'),
                            ('textarea', 'Multi-line Text'),
                            ('select', 'Dropdown'),
                            ('multiselect', 'Multi-select'),
                            ('checkbox', 'Checkbox'),
                            ('radio', 'Radio Buttons'),
                            ('date', 'Date'),
                            ('number', 'Number'),
                        ],
                        max_length=20,
                    ),
                ),
                ('required', models.BooleanField(default=False, help_text='Is this field required')),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text', max_length=200)),
                ('help_text', models.CharField(blank=True, help_text='Help text shown below field', max_length=500)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select field (list of strings)')),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='events.event'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Event Custom Field',
                'verbose_name_plural': 'Event Custom Fields',
                'db_table': 'event_custom_fields',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('speaker_names', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                (
                    'session_type',
                    models.CharField(
                        choices=[('live', 'Live Session'), ('recorded', 'Recorded/On-demand'), ('hybrid', 'Hybrid')],
                        default='live',
                        max_length=20,
                    ),
                ),
                ('has_separate_zoom', models.BooleanField(default=False)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=100)),
                ('zoom_join_url', models.URLField(blank=True, max_length=500)),
                ('zoom_host_url', models.URLField(blank=True, max_length=500)),
                ('cpd_credits', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                (
                    'minimum_attendance_percent',
                    models.PositiveIntegerField(default=80, help_text='Minimum attendance percentage for this session'),
                ),
                (
                    'event',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='events.event'),
                ),
            ],
            options={
                'verbose_name': 'Event Session',
                'verbose_name_plural': 'Event Sessions',
                'db_table': 'event_sessions',
                'ordering': ['event', 'order', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EventStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                (
                    'changed_by',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='events.event'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Event Status History',
                'verbose_name_plural': 'Event Status Histories',
                'db_table': 'event_status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
