# Generated by Django 6.0 on 2025-12-17 03:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='multi_session_completion_criteria',
            field=models.CharField(
                choices=[
                    ('all_sessions', 'All Sessions'),
                    ('percentage_of_sessions', 'Percentage of Sessions'),
                    ('min_sessions_count', 'Minimum Number of Sessions'),
                    ('total_minutes', 'Total Attendance Minutes (across all sessions)'),
                ],
                default='total_minutes',
                help_text='Criteria for marking a multi-session event as completed for certificate eligibility',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='multi_session_completion_value',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Value for multi-session completion criteria (e.g., 80 for percentage, 3 for min sessions)',
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='waitlist_auto_promote',
            field=models.BooleanField(default=False, help_text='Automatically promote from waitlist when spots open'),
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                (
                    'session_type',
                    models.CharField(
                        choices=[('live', 'Live Session'), ('recorded', 'Recorded/On-demand'), ('hybrid', 'Hybrid')],
                        default='live',
                        max_length=20,
                    ),
                ),
                ('has_separate_zoom', models.BooleanField(default=False)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=100)),
                ('zoom_join_url', models.URLField(blank=True, max_length=500)),
                ('zoom_host_url', models.URLField(blank=True, max_length=500)),
                ('cpd_credits', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    'minimum_attendance_percent',
                    models.PositiveIntegerField(default=80, help_text='Minimum attendance percentage for this session'),
                ),
                (
                    'is_mandatory',
                    models.BooleanField(default=True, help_text='Whether this session is required for certificate'),
                ),
                ('is_published', models.BooleanField(default=True)),
                (
                    'event',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='events.event'),
                ),
            ],
            options={
                'verbose_name': 'Event Session',
                'verbose_name_plural': 'Event Sessions',
                'db_table': 'event_sessions',
                'ordering': ['event', 'order', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('zoom_participant_id', models.CharField(blank=True, max_length=100)),
                ('join_events_count', models.PositiveIntegerField(default=0)),
                ('is_eligible', models.BooleanField(default=False, help_text='Met minimum attendance requirement')),
                ('override_eligible', models.BooleanField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                (
                    'override_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='session_attendance_overrides',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'registration',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='session_attendance',
                        to='registrations.registration',
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='events.eventsession'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Session Attendance',
                'verbose_name_plural': 'Session Attendance',
                'db_table': 'session_attendance',
                'unique_together': {('session', 'registration')},
            },
        ),
    ]
