# Generated by Django 6.0 on 2026-01-22 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionattendance',
            name='registration',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='session_attendance', to='registrations.registration'
            ),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='session',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='events.eventsession'
            ),
        ),
        migrations.AddField(
            model_name='speaker',
            name='owner',
            field=models.ForeignKey(
                help_text='User who manages this speaker profile',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='speakers',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(
                blank=True, help_text='Speakers for this event', related_name='events', to='events.speaker'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('session', 'registration')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['owner', 'status'], name='events_owner_i_4a461e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', '-starts_at'], name='events_status_3c2568_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['starts_at'], name='events_starts__f39f74_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['uuid'], name='events_uuid_5c78dd_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_slug_930801_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['zoom_meeting_id'], name='events_zoom_me_ba64fe_idx'),
        ),
    ]
