# Generated by Django 6.0 on 2026-01-04 20:20

from django.db import migrations, models


def convert_currency_to_uppercase(apps, schema_editor):
    """Convert existing lowercase currency codes to uppercase."""
    Event = apps.get_model('events', 'Event')
    Event.objects.filter(currency='usd').update(currency='USD')
    Event.objects.filter(currency='cad').update(currency='CAD')


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        # First, convert existing data
        migrations.RunPython(convert_currency_to_uppercase, migrations.RunPython.noop),
        # Then, alter the field with new choices
        migrations.AlterField(
            model_name='event',
            name='currency',
            field=models.CharField(
                choices=[('USD', 'US Dollar'), ('CAD', 'Canadian Dollar')],
                default='USD',
                help_text='Currency code (ISO 4217)',
                max_length=3,
            ),
        ),
    ]
