# Generated by Django 6.0 on 2026-01-17 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_badgestatushistory'),
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_issue_badges',
            field=models.BooleanField(default=False, help_text='Auto-issue badges when event completes'),
        ),
        migrations.AddField(
            model_name='event',
            name='badge_template',
            field=models.ForeignKey(
                blank=True,
                help_text='Template for badges',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='events',
                to='badges.badgetemplate',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='badges_enabled',
            field=models.BooleanField(default=False, help_text='Issue badges for this event'),
        ),
    ]
