# Generated by Django 6.0.3 on 2026-04-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='video_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Video conferencing settings — see VideoSettingsSerializer'),
        ),
    ]
