# Generated by Django 6.0 on 2025-12-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_multi_session_completion_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='format',
            field=models.CharField(
                choices=[('online', 'Online'), ('in-person', 'In Person'), ('hybrid', 'Hybrid')],
                default='online',
                help_text='Event format',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_closes_at',
            field=models.DateTimeField(blank=True, help_text='When registration closes', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_opens_at',
            field=models.DateTimeField(blank=True, help_text='When registration opens', null=True),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='speaker_names',
            field=models.CharField(blank=True, help_text='Comma-separated list of speakers', max_length=500),
        ),
    ]
