# Generated by Django 6.0 on 2026-01-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_badge_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='zoom_error',
            field=models.TextField(blank=True, help_text='Last Zoom integration error message'),
        ),
    ]
