# Generated by Django 6.0 on 2026-01-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_update_currency_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='currency',
            field=models.CharField(
                choices=[
                    ('USD', 'US Dollar ($)'),
                    ('CAD', 'Canadian Dollar (CA$)'),
                    ('EUR', 'Euro (€)'),
                    ('GBP', 'British Pound (£)'),
                    ('AUD', 'Australian Dollar (A$)'),
                    ('JPY', 'Japanese Yen (¥)'),
                    ('INR', 'Indian Rupee (₹)'),
                ],
                default='USD',
                help_text='Currency code (ISO 4217)',
                max_length=3,
            ),
        ),
    ]
