# Generated by Django 6.0 on 2025-12-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_format_event_registration_closes_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_multi_session',
            field=models.BooleanField(default=False, help_text='Is this a multi-session event?'),
        ),
    ]
