# Generated by Django 6.0.3 on 2026-04-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_video_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('webinar', 'Webinar'), ('workshop', 'Workshop'), ('training', 'Training Session'), ('lecture', 'Lecture'), ('seminar', 'Seminar / Series'), ('other', 'Other')], default='webinar', help_text='Type of event', max_length=20),
        ),
    ]
