# Generated by Django 6.0 on 2026-01-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_zoom_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='zoom_error_at',
            field=models.DateTimeField(blank=True, help_text='When last Zoom error occurred', null=True),
        ),
    ]
