# Generated by Django 6.0.3 on 2026-04-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_offsets_minutes',
            field=models.JSONField(blank=True, default=list, help_text='List of minutes-before-start to send reminders (e.g. [10080, 1440, 60, 0]).'),
        ),
    ]
