# Generated by Django 6.0 on 2025-12-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_is_multi_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('webinar', 'Webinar'), ('workshop', 'Workshop'), ('training', 'Training Session'), ('lecture', 'Lecture'), ('other', 'Other')], default='webinar', help_text='Type of event', max_length=20),
        ),
    ]
