# Generated by Django 6.0 on 2025-12-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(
                blank=True, help_text='Featured image upload', null=True, upload_to='events/featured_images/'
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Venue address or location description', max_length=500),
        ),
    ]
