# Generated by Django 6.0 on 2025-12-22 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_certificatetemplate_organization'),
        ('events', '0006_add_location_and_featured_image'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                help_text='Organization that owns this event (null for individual organizers)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='events',
                to='organizations.organization',
            ),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'status'], name='events_organiz_44b951_idx'),
        ),
    ]
