# Generated by Django 6.0 on 2025-12-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_organization_event_events_organiz_44b951_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsession',
            name='minimum_attendance_percent',
        ),
        migrations.RemoveField(
            model_name='sessionattendance',
            name='join_events_count',
        ),
        migrations.RemoveField(
            model_name='sessionattendance',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='sessionattendance',
            name='left_at',
        ),
        migrations.RemoveField(
            model_name='sessionattendance',
            name='override_by',
        ),
        migrations.RemoveField(
            model_name='sessionattendance',
            name='override_eligible',
        ),
        migrations.RemoveField(
            model_name='sessionattendance',
            name='override_reason',
        ),
        migrations.RemoveField(
            model_name='sessionattendance',
            name='zoom_participant_id',
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='speaker_names',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
