# Generated by Django 6.0 on 2025-12-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_organization_event_events_organiz_44b951_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(default='usd', help_text='Currency code (iso 4217)', max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ticket price (0.00 for free)', max_digits=10),
        ),
    ]
