# Generated by Django 6.0 on 2025-12-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_eventsession_minimum_attendance_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsession',
            name='minimum_attendance_percent',
            field=models.PositiveIntegerField(default=80, help_text='Minimum attendance percentage for this session'),
        ),
    ]
