# Generated by Django 6.0 on 2025-12-28 04:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_currency_event_price'),
        ('organizations', '0002_organization_stripe_account_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list, help_text='List of learning objectives (strings)'),
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('name', models.CharField(help_text='Speaker full name', max_length=200)),
                ('bio', models.TextField(help_text='Speaker biography')),
                ('qualifications', models.TextField(help_text='Professional qualifications/credentials')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/photos/')),
                ('email', models.EmailField(blank=True, help_text='Contact email (internal use)', max_length=254)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this speaker profile is active')),
                (
                    'organization',
                    models.ForeignKey(
                        blank=True,
                        help_text='Organization that owns this speaker profile',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='speakers',
                        to='organizations.organization',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        help_text='User who manages this speaker profile',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='speakers',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
                'db_table': 'speakers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(
                blank=True, help_text='Speakers for this event', related_name='events', to='events.speaker'
            ),
        ),
    ]
