# Generated by Django 6.0 on 2025-12-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_learning_objectives_speaker_event_speakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='require_feedback_for_certificate',
            field=models.BooleanField(
                default=False, help_text='Require attendees to submit feedback before downloading/accessing certificate'
            ),
        ),
    ]
