# Generated by Django 6.0 on 2026-01-16 21:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField()),
                ('due_days_after_release', models.PositiveIntegerField(default=7)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('passing_score', models.PositiveIntegerField(default=70)),
                ('allow_resubmission', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                (
                    'submission_type',
                    models.CharField(
                        choices=[
                            ('text', 'Text Response'),
                            ('file', 'File Upload'),
                            ('url', 'URL/Link'),
                            ('mixed', 'Mixed (Text + File)'),
                        ],
                        default='text',
                        max_length=20,
                    ),
                ),
                ('rubric', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'assignments',
                'ordering': ['module', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Course Announcement',
                'verbose_name_plural': 'Course Announcements',
                'db_table': 'course_announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending Approval'),
                            ('active', 'Active'),
                            ('completed', 'Completed'),
                            ('dropped', 'Dropped'),
                            ('expired', 'Expired'),
                        ],
                        db_index=True,
                        default='active',
                        max_length=20,
                    ),
                ),
                (
                    'access_type',
                    models.CharField(
                        choices=[
                            ('lifetime', 'Lifetime Access'),
                            ('limited', 'Limited Access'),
                            ('subscription', 'Subscription Access'),
                        ],
                        default='lifetime',
                        max_length=20,
                    ),
                ),
                (
                    'stripe_checkout_session_id',
                    models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=255, null=True),
                ),
                ('zoom_join_url', models.URLField(blank=True, help_text='Unique Zoom join URL', max_length=500)),
                ('zoom_registrant_id', models.CharField(blank=True, help_text='Zoom Registrant ID', max_length=255)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, help_text='When user enrolled')),
                ('started_at', models.DateTimeField(blank=True, help_text='When user started learning', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When user completed course', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When enrollment expires', null=True)),
                (
                    'progress_percent',
                    models.PositiveIntegerField(
                        default=0,
                        help_text='Overall progress percentage',
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ('modules_completed', models.PositiveIntegerField(default=0, help_text='Modules completed')),
                ('time_spent_minutes', models.PositiveIntegerField(default=0, help_text='Total time spent')),
                ('current_score', models.PositiveIntegerField(blank=True, help_text='Current aggregate score', null=True)),
                ('certificate_issued', models.BooleanField(default=False, help_text='Certificate issued')),
                ('certificate_issued_at', models.DateTimeField(blank=True, null=True)),
                (
                    'manually_completed',
                    models.BooleanField(default=False, help_text='Manually marked complete by instructor/manager'),
                ),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'db_table': 'course_enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in course')),
                ('is_required', models.BooleanField(default=True, help_text='Required for course completion')),
            ],
            options={
                'verbose_name': 'Course Module',
                'verbose_name_plural': 'Course Modules',
                'db_table': 'course_modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                (
                    'release_type',
                    models.CharField(
                        choices=[
                            ('immediate', 'Immediate'),
                            ('scheduled', 'Scheduled Date'),
                            ('days_after_registration', 'Days After Registration'),
                            ('prerequisite', 'After Prerequisite'),
                        ],
                        default='immediate',
                        max_length=30,
                    ),
                ),
                ('release_at', models.DateTimeField(blank=True, null=True)),
                ('release_days_after_registration', models.PositiveIntegerField(default=0)),
                (
                    'passing_score',
                    models.PositiveIntegerField(
                        default=70,
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ('cpd_credits', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cpd_type', models.CharField(blank=True, max_length=50)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Event Module',
                'verbose_name_plural': 'Event Modules',
                'db_table': 'event_modules',
                'ordering': ['event', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                (
                    'content_type',
                    models.CharField(
                        choices=[
                            ('video', 'Video'),
                            ('document', 'Document'),
                            ('text', 'Text/HTML'),
                            ('quiz', 'Quiz'),
                            ('external', 'External Link'),
                            ('lesson', 'Mixed Lesson'),
                        ],
                        max_length=20,
                    ),
                ),
                ('order', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('content_data', models.JSONField(default=dict)),
                (
                    'file',
                    models.FileField(
                        blank=True, help_text='Uploaded file (for document/video)', null=True, upload_to='learning/modules/'
                    ),
                ),
                ('is_required', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Module Content',
                'verbose_name_plural': 'Module Contents',
                'db_table': 'module_contents',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')],
                        default='not_started',
                        max_length=20,
                    ),
                ),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contents_completed', models.PositiveIntegerField(default=0)),
                ('contents_total', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Module Progress',
                'verbose_name_plural': 'Module Progress',
                'db_table': 'module_progress',
            },
        ),
        migrations.CreateModel(
            name='SubmissionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('submitted', 'Submitted'),
                            ('reviewed', 'Reviewed'),
                            ('graded', 'Graded'),
                            ('returned', 'Returned for Revision'),
                            ('approved', 'Approved'),
                            ('resubmitted', 'Resubmitted'),
                        ],
                        max_length=20,
                    ),
                ),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('rubric_scores', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Submission Review',
                'verbose_name_plural': 'Submission Reviews',
                'db_table': 'submission_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('submitted', 'Submitted'),
                            ('in_review', 'In Review'),
                            ('needs_revision', 'Needs Revision'),
                            ('graded', 'Graded'),
                            ('approved', 'Approved'),
                        ],
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.JSONField(default=dict)),
                ('file_url', models.URLField(blank=True, max_length=500)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                (
                    'assignment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning.assignment'
                    ),
                ),
                (
                    'graded_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='graded_submissions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'registration',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='assignment_submissions',
                        to='registrations.registration',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'db_table': 'assignment_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')],
                        default='not_started',
                        max_length=20,
                    ),
                ),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'progress_percent',
                    models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
                ),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('last_position', models.JSONField(default=dict)),
                (
                    'registration',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='content_progress',
                        to='registrations.registration',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Content Progress',
                'verbose_name_plural': 'Content Progress',
                'db_table': 'content_progress',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('title', models.CharField(help_text='Course title', max_length=255)),
                (
                    'format',
                    models.CharField(
                        choices=[('online', 'Online (Self-Paced)'), ('hybrid', 'Hybrid (Includes Live Sessions)')],
                        default='online',
                        help_text='Delivery format',
                        max_length=20,
                    ),
                ),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Course description', max_length=5000)),
                ('short_description', models.CharField(blank=True, help_text='Brief description for listings', max_length=300)),
                (
                    'featured_image',
                    models.ImageField(blank=True, help_text='Featured image', null=True, upload_to='courses/images/'),
                ),
                ('featured_image_url', models.URLField(blank=True, help_text='External featured image URL')),
                ('zoom_meeting_id', models.CharField(blank=True, help_text='Zoom Meeting ID', max_length=100)),
                ('zoom_meeting_url', models.URLField(blank=True, help_text='Zoom Join URL')),
                ('zoom_meeting_password', models.CharField(blank=True, help_text='Zoom Meeting Password', max_length=50)),
                ('zoom_webinar_id', models.CharField(blank=True, help_text='Zoom Webinar ID (if webinar)', max_length=100)),
                ('zoom_registrant_id', models.CharField(blank=True, help_text='Zoom Registrant tracking', max_length=255)),
                ('live_session_start', models.DateTimeField(blank=True, help_text='Start time for live session', null=True)),
                ('live_session_end', models.DateTimeField(blank=True, help_text='End time for live session', null=True)),
                (
                    'live_session_timezone',
                    models.CharField(default='UTC', help_text='Timezone for live sessions', max_length=64),
                ),
                (
                    'cpd_credits',
                    models.DecimalField(decimal_places=2, default=0, help_text='Total CPD credits for course', max_digits=5),
                ),
                ('cpd_type', models.CharField(blank=True, help_text='Type of CPD credits', max_length=50)),
                (
                    'status',
                    models.CharField(
                        choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')],
                        db_index=True,
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('is_public', models.BooleanField(default=True, help_text='Visible in public listings')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/')),
                ('price_cents', models.PositiveIntegerField(default=0, help_text='Price in cents (0 for free)')),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('stripe_product_id', models.CharField(blank=True, help_text='Stripe Product ID', max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID', max_length=255)),
                ('enrollment_open', models.BooleanField(default=True, help_text='Accept new enrollments')),
                (
                    'max_enrollments',
                    models.PositiveIntegerField(blank=True, help_text='Maximum enrollments (null = unlimited)', null=True),
                ),
                (
                    'enrollment_requires_approval',
                    models.BooleanField(default=False, help_text='Require approval for enrollment'),
                ),
                (
                    'estimated_hours',
                    models.DecimalField(decimal_places=1, default=0, help_text='Estimated hours to complete', max_digits=5),
                ),
                (
                    'passing_score',
                    models.PositiveIntegerField(
                        default=70,
                        help_text='Minimum score to pass (0-100)',
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ('certificates_enabled', models.BooleanField(default=True, help_text='Issue certificates on completion')),
                ('auto_issue_certificates', models.BooleanField(default=True, help_text='Auto-issue when course is completed')),
                ('enrollment_count', models.PositiveIntegerField(default=0, help_text='Total enrollments')),
                ('completion_count', models.PositiveIntegerField(default=0, help_text='Completed enrollments')),
                ('module_count', models.PositiveIntegerField(default=0, help_text='Number of modules')),
                (
                    'certificate_template',
                    models.ForeignKey(
                        blank=True,
                        help_text='Template for certificates',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='courses',
                        to='certificates.certificatetemplate',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        help_text='User who created this course',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_courses',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
    ]
