# Generated by Django 6.0 on 2026-01-16 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('learning', '0001_initial'),
        ('organizations', '0001_initial'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                help_text='Organization that owns this course (null for personal LMS plans)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='courses',
                to='organizations.organization',
            ),
        ),
        migrations.AddField(
            model_name='courseannouncement',
            name='course',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='learning.course'
            ),
        ),
        migrations.AddField(
            model_name='courseannouncement',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='course_announcements',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.course'
            ),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='manually_completed_by',
            field=models.ForeignKey(
                blank=True,
                help_text='User who manually marked this enrollment complete',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='manual_course_completions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='contentprogress',
            name='course_enrollment',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='content_progress',
                to='learning.courseenrollment',
            ),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='course_enrollment',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assignment_submissions',
                to='learning.courseenrollment',
            ),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.course'),
        ),
        migrations.AddField(
            model_name='eventmodule',
            name='event',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='events.event'
            ),
        ),
        migrations.AddField(
            model_name='eventmodule',
            name='prerequisite_module',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='dependent_modules',
                to='learning.eventmodule',
            ),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='module',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='learning.eventmodule'
            ),
        ),
        migrations.AddField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='learning.eventmodule'
            ),
        ),
        migrations.AddField(
            model_name='modulecontent',
            name='module',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='learning.eventmodule'
            ),
        ),
        migrations.AddField(
            model_name='contentprogress',
            name='content',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='learning.modulecontent'
            ),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='course_enrollment',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='module_progress',
                to='learning.courseenrollment',
            ),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='module',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='learning.eventmodule'
            ),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='registration',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='module_progress',
                to='registrations.registration',
            ),
        ),
        migrations.AddField(
            model_name='submissionreview',
            name='reviewer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='submission_reviews',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='submissionreview',
            name='submission',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning.assignmentsubmission'
            ),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='courses_status_67f368_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['organization', 'status'], name='courses_organiz_0c978e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_public', 'status'], name='courses_is_publ_0b1ee5_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(
                condition=models.Q(('organization__isnull', False)),
                fields=('organization', 'slug'),
                name='unique_course_slug_per_organization',
            ),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(
                condition=models.Q(('organization__isnull', True)),
                fields=('created_by', 'slug'),
                name='unique_course_slug_per_owner',
            ),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['status'], name='course_enro_status_a2415a_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course', 'status'], name='course_enro_course__37db5f_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', 'status'], name='course_enro_user_id_070106_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('course', 'user')},
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'registration'], name='assignment__assignm_466b11_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'course_enrollment'], name='assignment__assignm_009025_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['status'], name='assignment__status_cd5870_idx'),
        ),
        migrations.AddIndex(
            model_name='eventmodule',
            index=models.Index(fields=['event', 'order'], name='event_modul_event_i_fa7027_idx'),
        ),
        migrations.AddIndex(
            model_name='eventmodule',
            index=models.Index(fields=['is_published'], name='event_modul_is_publ_e65944_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventmodule',
            unique_together={('event', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='modulecontent',
            unique_together={('module', 'order')},
        ),
        migrations.AddConstraint(
            model_name='contentprogress',
            constraint=models.UniqueConstraint(
                condition=models.Q(('registration__isnull', False)),
                fields=('registration', 'content'),
                name='unique_registration_content',
            ),
        ),
        migrations.AddConstraint(
            model_name='contentprogress',
            constraint=models.UniqueConstraint(
                condition=models.Q(('course_enrollment__isnull', False)),
                fields=('course_enrollment', 'content'),
                name='unique_enrollment_content',
            ),
        ),
        migrations.AddConstraint(
            model_name='moduleprogress',
            constraint=models.UniqueConstraint(
                condition=models.Q(('registration__isnull', False)),
                fields=('registration', 'module'),
                name='unique_registration_module',
            ),
        ),
        migrations.AddConstraint(
            model_name='moduleprogress',
            constraint=models.UniqueConstraint(
                condition=models.Q(('course_enrollment__isnull', False)),
                fields=('course_enrollment', 'module'),
                name='unique_enrollment_module',
            ),
        ),
    ]
