# Generated by Django 6.0 on 2025-12-22 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_organization_event_events_organiz_44b951_idx'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodule',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='events.event'),
        ),
    ]
