# Generated by Django 6.0 on 2026-01-20 01:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='file_size_bytes',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='file_type',
            field=models.CharField(blank=True, help_text='File MIME type', max_length=100),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_file',
            field=models.FileField(
                blank=True,
                help_text='Student submission file (PDF, DOC, DOCX, TXT, ZIP, images)',
                null=True,
                upload_to='assignments/submissions/%Y/%m/',
            ),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file_url',
            field=models.URLField(
                blank=True, help_text='External file URL (optional, for backwards compatibility)', max_length=500
            ),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('attempt_number', models.PositiveIntegerField(help_text='Attempt number for this user on this quiz')),
                (
                    'status',
                    models.CharField(
                        choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded')],
                        default='in_progress',
                        max_length=20,
                    ),
                ),
                (
                    'submitted_answers',
                    models.JSONField(default=dict, help_text="User's submitted answers: {question_id: selected_option_id(s)}"),
                ),
                (
                    'score',
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text='Score as percentage (0-100)', max_digits=5, null=True
                    ),
                ),
                ('passed', models.BooleanField(default=False, help_text='Whether the attempt passed')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When attempt started')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When attempt submitted', null=True)),
                ('graded_at', models.DateTimeField(blank=True, help_text='When attempt was graded', null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, help_text='Time spent on quiz')),
                (
                    'content',
                    models.ForeignKey(
                        help_text='The quiz content being attempted',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='quiz_attempts',
                        to='learning.modulecontent',
                    ),
                ),
                (
                    'course_enrollment',
                    models.ForeignKey(
                        blank=True,
                        help_text='Course enrollment (for course-based quizzes)',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='quiz_attempts',
                        to='learning.courseenrollment',
                    ),
                ),
                (
                    'registration',
                    models.ForeignKey(
                        blank=True,
                        help_text='Registration (for event-based quizzes)',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='quiz_attempts',
                        to='registrations.registration',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'db_table': 'quiz_attempts',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['content', 'registration'], name='quiz_attemp_content_33cfe6_idx'),
                    models.Index(fields=['content', 'course_enrollment'], name='quiz_attemp_content_328b55_idx'),
                    models.Index(fields=['status'], name='quiz_attemp_status_02023c_idx'),
                ],
            },
        ),
    ]
