# Generated by Django 6.0 on 2026-01-08 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        ('registrations', '0007_add_stripe_tax_transaction_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='course_enrollment',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assignment_submissions',
                to='learning.courseenrollment',
            ),
        ),
        migrations.AddField(
            model_name='contentprogress',
            name='course_enrollment',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='content_progress',
                to='learning.courseenrollment',
            ),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='course_enrollment',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='module_progress',
                to='learning.courseenrollment',
            ),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='registration',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assignment_submissions',
                to='registrations.registration',
            ),
        ),
        migrations.AlterField(
            model_name='contentprogress',
            name='registration',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='content_progress',
                to='registrations.registration',
            ),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='registration',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='module_progress',
                to='registrations.registration',
            ),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'course_enrollment'], name='assignment__assignm_009025_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentprogress',
            constraint=models.UniqueConstraint(
                condition=models.Q(('registration__isnull', False)),
                fields=('registration', 'content'),
                name='unique_registration_content',
            ),
        ),
        migrations.AddConstraint(
            model_name='contentprogress',
            constraint=models.UniqueConstraint(
                condition=models.Q(('course_enrollment__isnull', False)),
                fields=('course_enrollment', 'content'),
                name='unique_enrollment_content',
            ),
        ),
        migrations.AddConstraint(
            model_name='moduleprogress',
            constraint=models.UniqueConstraint(
                condition=models.Q(('registration__isnull', False)),
                fields=('registration', 'module'),
                name='unique_registration_module',
            ),
        ),
        migrations.AddConstraint(
            model_name='moduleprogress',
            constraint=models.UniqueConstraint(
                condition=models.Q(('course_enrollment__isnull', False)),
                fields=('course_enrollment', 'module'),
                name='unique_enrollment_module',
            ),
        ),
    ]
