# Generated by Django 6.0.3 on 2026-04-28 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='comped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_enrollments_comped', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='invitation_email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email the invite was sent to. Set when user=NULL; cleared on link.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='was_comped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['invitation_email'], name='course_enro_invitat_133f44_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('course', 'user'), name='unique_user_per_course'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('invitation_email__isnull', False), ('user__isnull', True)), fields=('course', 'invitation_email'), name='unique_guest_invite_per_course'),
        ),
    ]
