# Generated by Django 6.0 on 2026-01-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_eventmodule_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecontent',
            name='content_type',
            field=models.CharField(
                choices=[
                    ('video', 'Video'),
                    ('document', 'Document'),
                    ('text', 'Text/HTML'),
                    ('quiz', 'Quiz'),
                    ('external', 'External Link'),
                    ('lesson', 'Mixed Lesson'),
                ],
                max_length=20,
            ),
        ),
    ]
