# Generated by Django 6.0 on 2026-01-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_contentprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
        migrations.AddField(
            model_name='course',
            name='format',
            field=models.CharField(
                choices=[('online', 'Online (Self-Paced)'), ('hybrid', 'Hybrid (Includes Live Sessions)')],
                default='online',
                help_text='Delivery format',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='course',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe Product ID', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_cents',
            field=models.PositiveIntegerField(default=0, help_text='Price in cents (0 for free)'),
        ),
    ]
