# Generated by Django 6.0 on 2026-01-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_remove_course_is_free_course_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='live_session_end',
            field=models.DateTimeField(blank=True, help_text='End time for live session', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='live_session_start',
            field=models.DateTimeField(blank=True, help_text='Start time for live session', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='live_session_timezone',
            field=models.CharField(default='UTC', help_text='Timezone for live sessions', max_length=64),
        ),
        migrations.AddField(
            model_name='course',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, help_text='Zoom Meeting ID', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='zoom_meeting_password',
            field=models.CharField(blank=True, help_text='Zoom Meeting Password', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='zoom_meeting_url',
            field=models.URLField(blank=True, help_text='Zoom Join URL'),
        ),
        migrations.AddField(
            model_name='course',
            name='zoom_registrant_id',
            field=models.CharField(blank=True, help_text='Zoom Registrant tracking', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='zoom_webinar_id',
            field=models.CharField(blank=True, help_text='Zoom Webinar ID (if webinar)', max_length=100),
        ),
    ]
