# Generated by Django 6.0 on 2026-01-17 22:23

from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_add_badge_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='zoom_error',
            field=models.TextField(blank=True, help_text='Last Zoom integration error message'),
        ),
        migrations.AddField(
            model_name='course',
            name='zoom_error_at',
            field=models.DateTimeField(blank=True, help_text='When last Zoom error occurred', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='zoom_meeting_uuid',
            field=models.CharField(blank=True, help_text='Zoom Meeting UUID', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='zoom_settings',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Zoom meeting settings (enabled, waiting_room, etc.)',
                validators=[common.validators.validate_zoom_settings_schema],
            ),
        ),
        migrations.AddField(
            model_name='course',
            name='zoom_start_url',
            field=models.URLField(blank=True, help_text='Zoom Start URL for host', max_length=2000),
        ),
    ]
