# Generated by Django 6.0.3 on 2026-04-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_normalize_module_content_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='format',
            field=models.CharField(choices=[('online', 'Online (Self-Paced)'), ('live', 'Live (Lectures)'), ('hybrid', 'Hybrid (Modules + Live Sessions)')], default='online', help_text='Delivery format', max_length=20),
        ),
        migrations.AlterField(
            model_name='modulecontent',
            name='content_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
