# Generated by Django 6.0 on 2026-01-17 22:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_add_course_zoom_auto_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('title', models.CharField(help_text='Session title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Session description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                (
                    'session_type',
                    models.CharField(
                        choices=[('live', 'Live Session'), ('recorded', 'Recorded/On-demand'), ('hybrid', 'Hybrid')],
                        default='live',
                        max_length=20,
                    ),
                ),
                ('starts_at', models.DateTimeField(help_text='Session start time')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration in minutes')),
                ('timezone', models.CharField(default='UTC', help_text='Session timezone', max_length=50)),
                ('zoom_meeting_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('zoom_meeting_uuid', models.CharField(blank=True, max_length=100)),
                ('zoom_join_url', models.URLField(blank=True, max_length=500)),
                ('zoom_start_url', models.URLField(blank=True, max_length=2000)),
                ('zoom_password', models.CharField(blank=True, max_length=50)),
                (
                    'zoom_settings',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Zoom meeting settings',
                        validators=[common.validators.validate_zoom_settings_schema],
                    ),
                ),
                ('zoom_error', models.TextField(blank=True, help_text='Last Zoom error message')),
                ('zoom_error_at', models.DateTimeField(blank=True, null=True)),
                (
                    'cpd_credits',
                    models.DecimalField(decimal_places=2, default=0, help_text='CPD credits for attending', max_digits=5),
                ),
                ('is_mandatory', models.BooleanField(default=True, help_text='Required for course completion')),
                (
                    'minimum_attendance_percent',
                    models.PositiveIntegerField(default=80, help_text='Minimum attendance percentage for eligibility'),
                ),
                ('is_published', models.BooleanField(default=True)),
                (
                    'course',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learning.course'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Course Session',
                'verbose_name_plural': 'Course Sessions',
                'db_table': 'course_sessions',
                'ordering': ['course', 'order', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('attendance_minutes', models.PositiveIntegerField(default=0, help_text='Minutes attended')),
                ('is_eligible', models.BooleanField(default=False, help_text='Met minimum attendance %')),
                ('zoom_participant_id', models.CharField(blank=True, max_length=255)),
                ('zoom_user_email', models.EmailField(blank=True, max_length=254)),
                ('zoom_join_time', models.DateTimeField(blank=True, null=True)),
                ('zoom_leave_time', models.DateTimeField(blank=True, null=True)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                (
                    'enrollment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='session_attendance',
                        to='learning.courseenrollment',
                    ),
                ),
                (
                    'override_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='course_attendance_overrides',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attendance_records',
                        to='learning.coursesession',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Course Session Attendance',
                'verbose_name_plural': 'Course Session Attendance',
                'db_table': 'course_session_attendance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coursesession',
            index=models.Index(fields=['course', 'starts_at'], name='course_sess_course__5b7d12_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesession',
            index=models.Index(fields=['zoom_meeting_id'], name='course_sess_zoom_me_88abcf_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesessionattendance',
            index=models.Index(fields=['session', 'enrollment'], name='course_sess_session_780406_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesessionattendance',
            index=models.Index(fields=['zoom_user_email'], name='course_sess_zoom_us_8034ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursesessionattendance',
            unique_together={('session', 'enrollment')},
        ),
    ]
