# Generated by Django 6.0.3 on 2026-04-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_course_format_alter_modulecontent_content_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='actual_end_at',
            field=models.DateTimeField(blank=True, help_text='When the session actually ended', null=True),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='actual_start_at',
            field=models.DateTimeField(blank=True, help_text='When the session actually started', null=True),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='cancelled_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='recording_auto_publish',
            field=models.BooleanField(default=False, help_text='Auto-publish recording when available'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='recording_enabled',
            field=models.BooleanField(default=False, help_text='Enable cloud recording'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20),
        ),
    ]
