# Generated by Django 6.0 on 2026-01-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_add_course_session_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hybrid_completion_criteria',
            field=models.CharField(
                choices=[
                    ('modules_only', 'Complete All Required Modules'),
                    ('sessions_only', 'Attend All Required Sessions'),
                    ('both', 'Complete Modules AND Attend Sessions'),
                    ('either', 'Complete Modules OR Attend Sessions'),
                    ('min_sessions', 'Complete Modules + Minimum Sessions'),
                ],
                default='both',
                help_text='How to determine completion for hybrid courses',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='course',
            name='min_sessions_required',
            field=models.PositiveIntegerField(
                default=1, help_text='Minimum sessions to attend (when using MIN_SESSIONS criteria)'
            ),
        ),
    ]
