# Generated by Django 6.0.3 on 2026-04-17 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_coursesession_actual_end_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coursesessionattendance',
            name='course_sess_zoom_us_8034ca_idx',
        ),
        migrations.RenameField(
            model_name='coursesessionattendance',
            old_name='zoom_join_time',
            new_name='join_time',
        ),
        migrations.RenameField(
            model_name='coursesessionattendance',
            old_name='zoom_leave_time',
            new_name='leave_time',
        ),
        migrations.RenameField(
            model_name='coursesessionattendance',
            old_name='zoom_user_email',
            new_name='participant_email',
        ),
        migrations.RenameField(
            model_name='coursesessionattendance',
            old_name='zoom_participant_id',
            new_name='participant_id',
        ),
        migrations.AddIndex(
            model_name='coursesessionattendance',
            index=models.Index(fields=['participant_email'], name='course_sess_partici_aa4fbd_idx'),
        ),
    ]
