# Generated by Django 6.0.3 on 2026-04-17 05:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_remove_coursesessionattendance_course_sess_zoom_us_8034ca_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='programs/images/')),
                ('featured_image_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('price_cents', models.PositiveIntegerField(default=0, help_text='Bundle price in cents')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255)),
                ('course_count', models.PositiveIntegerField(default=0)),
                ('enrollment_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_memberships', to='learning.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='learning.program')),
            ],
            options={
                'verbose_name': 'Program Course',
                'verbose_name_plural': 'Program Courses',
                'db_table': 'program_courses',
                'ordering': ['program', 'order'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='courses',
            field=models.ManyToManyField(related_name='programs', through='learning.ProgramCourse', to='learning.course'),
        ),
        migrations.CreateModel(
            name='ProgramEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], db_index=True, default='pending', max_length=20)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('course_enrollments_seeded', models.BooleanField(default=False, help_text='True once member-course CourseEnrollments have been auto-created.')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Program Enrollment',
                'verbose_name_plural': 'Program Enrollments',
                'db_table': 'program_enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='programcourse',
            constraint=models.UniqueConstraint(fields=('program', 'course'), name='unique_program_course'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['status'], name='programs_status_1f33ec_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['is_public', 'status'], name='programs_is_publ_15720f_idx'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('created_by', 'slug'), name='unique_program_slug_per_owner'),
        ),
        migrations.AddIndex(
            model_name='programenrollment',
            index=models.Index(fields=['user', 'status'], name='program_enr_user_id_5f86d9_idx'),
        ),
        migrations.AddIndex(
            model_name='programenrollment',
            index=models.Index(fields=['program', 'status'], name='program_enr_program_9369f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='programenrollment',
            constraint=models.UniqueConstraint(fields=('user', 'program'), name='unique_program_enrollment_per_user'),
        ),
    ]
