# Generated by Django 6.0 on 2026-01-12 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_add_course_announcements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='manually_completed',
            field=models.BooleanField(default=False, help_text='Manually marked complete by instructor/manager'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='manually_completed_by',
            field=models.ForeignKey(
                blank=True,
                help_text='User who manually marked this enrollment complete',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='manual_course_completions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='courseannouncement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
