# Generated by Django 6.0.3 on 2026-04-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_program_programcourse_program_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_closes_at',
            field=models.DateTimeField(blank=True, help_text='Enrollments close at this time', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_opens_at',
            field=models.DateTimeField(blank=True, help_text='Enrollments accepted from this time', null=True),
        ),
    ]
