# Generated by Django 6.0 on 2026-01-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_add_course_completion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='access_type',
            field=models.CharField(
                choices=[
                    ('lifetime', 'Lifetime Access'),
                    ('limited', 'Limited Access'),
                    ('subscription', 'Subscription Access'),
                ],
                default='lifetime',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=255, null=True),
        ),
    ]
