# Generated by Django 6.0.3 on 2026-04-20 18:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_course_enrollment_closes_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted (null if active)', null=True)),
                ('title', models.CharField(max_length=255)),
                ('body_html', models.TextField()),
                ('body_plain', models.TextField(blank=True)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_threads', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to='learning.course')),
                ('mentions', models.ManyToManyField(blank=True, related_name='discussion_thread_mentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discussion Thread',
                'verbose_name_plural': 'Discussion Threads',
                'db_table': 'discussion_threads',
                'ordering': ['-is_pinned', '-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted (null if active)', null=True)),
                ('body_html', models.TextField()),
                ('body_plain', models.TextField(blank=True)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_replies', to=settings.AUTH_USER_MODEL)),
                ('mentions', models.ManyToManyField(blank=True, related_name='discussion_reply_mentions', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='learning.discussionthread')),
            ],
            options={
                'verbose_name': 'Discussion Reply',
                'verbose_name_plural': 'Discussion Replies',
                'db_table': 'discussion_replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('off_topic', 'Off-topic'), ('other', 'Other')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved_kept', 'Resolved — Content Kept'), ('resolved_hidden', 'Resolved — Content Hidden')], db_index=True, default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_flags_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_flags_resolved', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='learning.discussionreply')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='learning.discussionthread')),
            ],
            options={
                'verbose_name': 'Discussion Flag',
                'verbose_name_plural': 'Discussion Flags',
                'db_table': 'discussion_flags',
            },
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['course', '-last_activity_at'], name='discussion__course__50a9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['course', 'is_pinned'], name='discussion__course__613a83_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionreply',
            index=models.Index(fields=['thread', 'created_at'], name='discussion__thread__8faa27_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionflag',
            index=models.Index(fields=['status', '-created_at'], name='discussion__status_9acc22_idx'),
        ),
        migrations.AddConstraint(
            model_name='discussionflag',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reply__isnull', True), ('thread__isnull', False)), models.Q(('reply__isnull', False), ('thread__isnull', True)), _connector='OR'), name='discussion_flag_exactly_one_target'),
        ),
    ]
