# Generated by Django 6.0 on 2026-01-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_courseenrollment_access_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='zoom_join_url',
            field=models.URLField(blank=True, help_text='Unique Zoom join URL', max_length=500),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='zoom_registrant_id',
            field=models.CharField(blank=True, help_text='Zoom Registrant ID', max_length=255),
        ),
    ]
