# Generated by Django 6.0.3 on 2026-04-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_discussion_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestaff',
            name='role',
            field=models.CharField(default='instructor', max_length=30),
        ),
    ]
