# Generated by Django 6.0.3 on 2026-04-24 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_alter_coursestaff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='from_program_enrollment',
            field=models.ForeignKey(blank=True, help_text='The ProgramEnrollment that seeded this row, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeded_course_enrollments', to='learning.programenrollment'),
        ),
    ]
