# Generated by Django 6.0.3 on 2026-04-24 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_courseenrollment_from_program_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseannouncement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Course/Program Announcement', 'verbose_name_plural': 'Course/Program Announcements'},
        ),
        migrations.AddField(
            model_name='courseannouncement',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='learning.program'),
        ),
        migrations.AlterField(
            model_name='courseannouncement',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='learning.course'),
        ),
    ]
