# Generated by Django 6.0.3 on 2026-04-25 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_alter_courseannouncement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='delivery_mode',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person'), ('hybrid', 'Hybrid (in-person + remote)')], default='online', help_text='How attendees join: online, in person, or both.', max_length=20),
        ),
        migrations.CreateModel(
            name='CourseSessionRecordingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('watch_seconds', models.PositiveIntegerField(default=0, help_text='Cumulative seconds watched')),
                ('last_position_seconds', models.PositiveIntegerField(default=0, help_text='Resume point')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the learner watched to the end', null=True)),
                ('course_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_views', to='learning.courseenrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_views', to='learning.coursesession')),
            ],
            options={
                'verbose_name': 'Course Session Recording View',
                'verbose_name_plural': 'Course Session Recording Views',
                'db_table': 'course_session_recording_views',
                'constraints': [models.UniqueConstraint(fields=('course_enrollment', 'session'), name='unique_enrollment_session_recording')],
            },
        ),
    ]
