# Generated by Django 6.0.3 on 2026-04-27 02:37

import billing.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('amount_cents', models.PositiveIntegerField(help_text='Total charged in cents (subtotal + tax)')),
                ('subtotal_cents', models.PositiveIntegerField(default=0, help_text='Pre-tax amount in cents')),
                ('tax_cents', models.PositiveIntegerField(default=0, help_text='Stripe automatic_tax amount in cents')),
                ('currency', models.CharField(default=billing.models._default_currency, max_length=3)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Course Purchase',
                'verbose_name_plural': 'Course Purchases',
                'db_table': 'course_purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('stripe_dispute_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default=billing.models._default_currency, max_length=3)),
                ('reason', models.CharField(choices=[('credit_not_processed', 'Credit not processed'), ('duplicate', 'Duplicate'), ('fraudulent', 'Fraudulent'), ('general', 'General'), ('incorrect_account_details', 'Incorrect account details'), ('insufficient_funds', 'Insufficient funds'), ('product_not_received', 'Product not received'), ('product_unacceptable', 'Product unacceptable'), ('subscription_canceled', 'Subscription canceled'), ('unrecognized', 'Unrecognized'), ('other', 'Other')], default='general', max_length=64)),
                ('status', models.CharField(choices=[('warning_needs_response', 'Warning — Needs Response'), ('warning_under_review', 'Warning — Under Review'), ('warning_closed', 'Warning — Closed'), ('needs_response', 'Needs Response'), ('under_review', 'Under Review'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='needs_response', max_length=64)),
                ('evidence_due_by', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('stripe_payment_method_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('card_brand', models.CharField(blank=True, max_length=50)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('card_exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('billing_name', models.CharField(blank=True, max_length=255)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('stripe_refund_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(db_index=True, max_length=255)),
                ('amount_cents', models.PositiveIntegerField(help_text='Amount refunded in cents')),
                ('currency', models.CharField(default=billing.models._default_currency, max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('reason', models.CharField(choices=[('duplicate', 'Duplicate'), ('fraudulent', 'Fraudulent'), ('requested_by_customer', 'Requested by Customer'), ('other', 'Other')], default='requested_by_customer', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Refund Record',
                'verbose_name_plural': 'Refund Records',
                'db_table': 'refund_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('event_id', models.CharField(help_text='Stripe event id (evt_...)', max_length=80, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('payload', models.JSONField(default=dict, help_text='Snapshot of event body as received from Stripe')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Stripe Event',
                'verbose_name_plural': 'Stripe Events',
                'db_table': 'stripe_events',
                'ordering': ['-received_at'],
            },
        ),
    ]
