# Generated by Django 6.0 on 2025-12-17 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('stripe_payment_method_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('card_brand', models.CharField(blank=True, max_length=50)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('card_exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('billing_name', models.CharField(blank=True, max_length=255)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                (
                    'plan',
                    models.CharField(
                        choices=[
                            ('free', 'Free'),
                            ('starter', 'Starter'),
                            ('professional', 'Professional'),
                            ('enterprise', 'Enterprise'),
                        ],
                        default='free',
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('trialing', 'Trialing'),
                            ('active', 'Active'),
                            ('past_due', 'Past Due'),
                            ('canceled', 'Canceled'),
                            ('unpaid', 'Unpaid'),
                            ('incomplete', 'Incomplete'),
                            ('paused', 'Paused'),
                        ],
                        default='active',
                        max_length=20,
                    ),
                ),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('events_created_this_period', models.PositiveIntegerField(default=0)),
                ('certificates_issued_this_period', models.PositiveIntegerField(default=0)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('stripe_invoice_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='usd', max_length=3)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('open', 'Open'),
                            ('paid', 'Paid'),
                            ('void', 'Void'),
                            ('uncollectible', 'Uncollectible'),
                        ],
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('invoice_pdf_url', models.URLField(blank=True, max_length=500)),
                ('hosted_invoice_url', models.URLField(blank=True, max_length=500)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'subscription',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='invoices',
                        to='billing.subscription',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan'], name='subscriptio_plan_59e3ed_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='subscriptio_status_572d44_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['current_period_end'], name='subscriptio_current_0ac39a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_status_07776b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-created_at'], name='invoices_created_3daf52_idx'),
        ),
    ]
