# Generated by Django 6.0 on 2026-01-01 21:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('name', models.CharField(help_text='Product name (shown to customers)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                (
                    'stripe_product_id',
                    models.CharField(
                        blank=True, help_text='Stripe product ID (prod_...)', max_length=255, null=True, unique=True
                    ),
                ),
                ('is_active', models.BooleanField(default=True, help_text='Whether product is active')),
                (
                    'plan',
                    models.CharField(
                        choices=[('attendee', 'Attendee'), ('professional', 'Professional'), ('organization', 'Organization')],
                        help_text='Which subscription plan this product represents',
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    'trial_period_days',
                    models.PositiveIntegerField(
                        blank=True, help_text='Trial period in days (null = use global default)', null=True
                    ),
                ),
                (
                    'show_contact_sales',
                    models.BooleanField(
                        default=False, help_text="If true, hides pricing and shows 'Contact Sales' button instead"
                    ),
                ),
                (
                    'events_per_month',
                    models.PositiveIntegerField(blank=True, help_text='Max events per month (null = unlimited)', null=True),
                ),
                (
                    'certificates_per_month',
                    models.PositiveIntegerField(
                        blank=True, help_text='Max certificates per month (null = unlimited)', null=True
                    ),
                ),
                (
                    'max_attendees_per_event',
                    models.PositiveIntegerField(blank=True, help_text='Max attendees per event (null = unlimited)', null=True),
                ),
            ],
            options={
                'verbose_name': 'Stripe Product',
                'verbose_name_plural': 'Stripe Products',
                'db_table': 'stripe_products',
                'ordering': ['plan'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('stripe_payment_method_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('card_brand', models.CharField(blank=True, max_length=50)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('card_exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('billing_name', models.CharField(blank=True, max_length=255)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                (
                    'plan',
                    models.CharField(
                        choices=[('attendee', 'Attendee'), ('professional', 'Professional'), ('organization', 'Organization')],
                        default='attendee',
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('trialing', 'Trialing'),
                            ('active', 'Active'),
                            ('past_due', 'Past Due'),
                            ('canceled', 'Canceled'),
                            ('unpaid', 'Unpaid'),
                            ('incomplete', 'Incomplete'),
                            ('paused', 'Paused'),
                        ],
                        default='active',
                        max_length=20,
                    ),
                ),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('events_created_this_period', models.PositiveIntegerField(default=0)),
                ('certificates_issued_this_period', models.PositiveIntegerField(default=0)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('stripe_invoice_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='usd', max_length=3)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('open', 'Open'),
                            ('paid', 'Paid'),
                            ('void', 'Void'),
                            ('uncollectible', 'Uncollectible'),
                        ],
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('invoice_pdf_url', models.URLField(blank=True, max_length=500)),
                ('hosted_invoice_url', models.URLField(blank=True, max_length=500)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'subscription',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='invoices',
                        to='billing.subscription',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('amount_cents', models.PositiveIntegerField(help_text='Price in cents (e.g., 9900 = $99.00)')),
                ('currency', models.CharField(default='usd', max_length=3)),
                (
                    'billing_interval',
                    models.CharField(choices=[('month', 'Monthly'), ('year', 'Annual')], default='month', max_length=10),
                ),
                (
                    'stripe_price_id',
                    models.CharField(
                        blank=True, help_text='Stripe price ID (price_...)', max_length=255, null=True, unique=True
                    ),
                ),
                ('is_active', models.BooleanField(default=True, help_text='Whether price is available for new subscriptions')),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='billing.stripeproduct'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Stripe Price',
                'verbose_name_plural': 'Stripe Prices',
                'db_table': 'stripe_prices',
                'ordering': ['product', 'billing_interval'],
                'unique_together': {('product', 'billing_interval')},
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan'], name='subscriptio_plan_59e3ed_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='subscriptio_status_572d44_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['current_period_end'], name='subscriptio_current_0ac39a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_status_07776b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-created_at'], name='invoices_created_3daf52_idx'),
        ),
    ]
