# Generated by Django 6.0 on 2025-12-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(
                choices=[('attendee', 'Attendee'), ('organizer', 'Organizer'), ('organization', 'Organization')],
                default='attendee',
                max_length=20,
            ),
        ),
    ]
