# Generated by Django 6.0 on 2026-01-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeproduct',
            name='trial_period_days',
            field=models.PositiveIntegerField(default=30, help_text='Trial period in days'),
        ),
    ]
