# Generated by Django 6.0.3 on 2026-04-27 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('events', '0002_initial'),
        ('learning', '0001_initial'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchase',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='learning.course'),
        ),
        migrations.AddField(
            model_name='coursepurchase',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='events.event'),
        ),
        migrations.AddField(
            model_name='coursepurchase',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='learning.program'),
        ),
        migrations.AddField(
            model_name='coursepurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='course_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='billing.coursepurchase'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='registrations.registration'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='billing.coursepurchase'),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='registrations.registration'),
        ),
        migrations.AddIndex(
            model_name='stripeevent',
            index=models.Index(fields=['event_type', '-received_at'], name='stripe_even_event_t_86ab3a_idx'),
        ),
        migrations.AddIndex(
            model_name='stripeevent',
            index=models.Index(fields=['processed_at'], name='stripe_even_process_5f3d71_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursepurchase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('event__isnull', True), ('program__isnull', True)), models.Q(('course__isnull', True), ('event__isnull', False), ('program__isnull', True)), models.Q(('course__isnull', True), ('event__isnull', True), ('program__isnull', False)), _connector='OR'), name='purchase_one_target'),
        ),
        migrations.AddConstraint(
            model_name='coursepurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_checkout_session_id', ''), _negated=True), fields=('stripe_checkout_session_id',), name='uniq_purchase_per_checkout_session'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', '-created_at'], name='disputes_status_1f4293_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['evidence_due_by'], name='disputes_evidenc_80b4ab_idx'),
        ),
    ]
