# Generated by Django 6.0 on 2026-01-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='limits_override',
            field=models.JSONField(
                blank=True, help_text="Optional JSON dict to override plan limits (e.g., {'events_per_month': 5})", null=True
            ),
        ),
    ]
