# Generated by Django 6.0.3 on 2026-04-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('event_id', models.CharField(help_text='Stripe event id (evt_...)', max_length=80, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('payload', models.JSONField(default=dict, help_text='Snapshot of event body as received from Stripe')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Stripe Event',
                'verbose_name_plural': 'Stripe Events',
                'db_table': 'stripe_events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type', '-received_at'], name='stripe_even_event_t_86ab3a_idx'), models.Index(fields=['processed_at'], name='stripe_even_process_5f3d71_idx')],
            },
        ),
    ]
