# Generated by Django 6.0 on 2026-01-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_stripeproduct_trial_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeproduct',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=14, help_text='Grace period in days (after trial/subscription ends)'),
        ),
    ]
