# Generated by Django 6.0 on 2026-01-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_stripeproduct_grace_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeproduct',
            name='included_seats',
            field=models.PositiveIntegerField(default=0, help_text='Number of included seats (for organization plans)'),
        ),
        migrations.AddField(
            model_name='stripeproduct',
            name='seat_price_cents',
            field=models.PositiveIntegerField(default=0, help_text='Price per additional seat in cents'),
        ),
    ]
