# Generated by Django 6.0.3 on 2026-04-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_stripeevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionbillingconfig',
            name='stripe_publishable_key',
        ),
        migrations.RemoveField(
            model_name='institutionbillingconfig',
            name='stripe_secret_key',
        ),
        migrations.RemoveField(
            model_name='institutionbillingconfig',
            name='stripe_webhook_secret',
        ),
    ]
