# Generated by Django 6.0.3 on 2026-04-22 06:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_institutionbillingconfig_stripe_publishable_key_and_more'),
        ('registrations', '0004_remove_registration_billing_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('stripe_dispute_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='cad', max_length=3)),
                ('reason', models.CharField(choices=[('credit_not_processed', 'Credit not processed'), ('duplicate', 'Duplicate'), ('fraudulent', 'Fraudulent'), ('general', 'General'), ('incorrect_account_details', 'Incorrect account details'), ('insufficient_funds', 'Insufficient funds'), ('product_not_received', 'Product not received'), ('product_unacceptable', 'Product unacceptable'), ('subscription_canceled', 'Subscription canceled'), ('unrecognized', 'Unrecognized'), ('other', 'Other')], default='general', max_length=64)),
                ('status', models.CharField(choices=[('warning_needs_response', 'Warning — Needs Response'), ('warning_under_review', 'Warning — Under Review'), ('warning_closed', 'Warning — Closed'), ('needs_response', 'Needs Response'), ('under_review', 'Under Review'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='needs_response', max_length=64)),
                ('evidence_due_by', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('course_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='billing.coursepurchase')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='registrations.registration')),
            ],
            options={
                'db_table': 'disputes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='disputes_status_1f4293_idx'), models.Index(fields=['evidence_due_by'], name='disputes_evidenc_80b4ab_idx')],
            },
        ),
    ]
