# Generated by Django 6.0 on 2025-12-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_add_new_plan_tiers'),
        ('billing', '0005_simplify_pricing_tiers'),
    ]

    operations = []
