# Generated by Django 6.0 on 2026-01-10 03:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_add_lms_plan_and_course_limits'),
        ('events', '0004_add_more_currencies'),
        ('registrations', '0007_add_stripe_tax_transaction_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('stripe_connect_account_id', models.CharField(db_index=True, max_length=255)),
                ('stripe_payout_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('amount_cents', models.PositiveIntegerField(help_text='Amount in cents')),
                ('currency', models.CharField(default='usd', max_length=3)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('in_transit', 'In Transit'),
                            ('paid', 'Paid'),
                            ('failed', 'Failed'),
                            ('canceled', 'Canceled'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('arrival_date', models.DateField(blank=True, help_text='Expected arrival date', null=True)),
                ('destination_bank_last4', models.CharField(blank=True, max_length=4)),
                ('error_message', models.TextField(blank=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'verbose_name': 'Payout Request',
                'verbose_name_plural': 'Payout Requests',
                'db_table': 'payout_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('stripe_refund_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(db_index=True, max_length=255)),
                ('amount_cents', models.PositiveIntegerField(help_text='Amount refunded in cents')),
                ('currency', models.CharField(default='usd', max_length=3)),
                (
                    'platform_fee_reversed_cents',
                    models.IntegerField(default=0, help_text='Amount of platform fee returned (if any)'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('succeeded', 'Succeeded'),
                            ('failed', 'Failed'),
                            ('canceled', 'Canceled'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                (
                    'reason',
                    models.CharField(
                        choices=[
                            ('duplicate', 'Duplicate'),
                            ('fraudulent', 'Fraudulent'),
                            ('requested_by_customer', 'Requested by Customer'),
                            ('expired_uncaptured', 'Expired Uncaptured Charge'),
                            ('other', 'Other'),
                        ],
                        default='requested_by_customer',
                        max_length=50,
                    ),
                ),
                ('description', models.TextField(blank=True, help_text='Internal notes or description')),
                ('error_message', models.TextField(blank=True)),
                (
                    'processed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='processed_refunds',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'registration',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='refunds',
                        to='registrations.registration',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Refund Record',
                'verbose_name_plural': 'Refund Records',
                'db_table': 'refund_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reversed', models.BooleanField(default=False, help_text='If transfer was reversed (e.g. refund)')),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'event',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='transfers',
                        to='events.event',
                    ),
                ),
                (
                    'recipient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='received_transfers',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'registration',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='transfers',
                        to='registrations.registration',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Transfer Record',
                'verbose_name_plural': 'Transfer Records',
                'db_table': 'transfer_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
