# Generated by Django 6.0.3 on 2026-04-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_dispute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstitutionBillingConfig',
        ),
        migrations.RemoveField(
            model_name='institutionplan',
            name='included_courses',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscriptio_status_572d44_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscriptio_current_0ac39a_idx',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='institution_plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='InstitutionPlan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
