# Generated by Django 6.0.3 on 2026-04-24 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_delete_institutionbillingconfig_and_more'),
        ('learning', '0011_courseenrollment_from_program_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchase',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='learning.program'),
        ),
    ]
