# Generated by Django - Manual migration
"""
Add contact_sales flag and feature limit fields to StripeProduct.

This migration adds:
- show_contact_sales: Boolean flag to show "Contact Sales" instead of pricing
- events_per_month: Max events per month limit
- certificates_per_month: Max certificates per month limit
- max_attendees_per_event: Max attendees per event limit

Also populates the feature limits from PLAN_LIMITS for existing products.
"""

from django.db import migrations, models


def populate_feature_limits(apps, schema_editor):
    """Populate feature limits for existing products."""
    StripeProduct = apps.get_model('billing', 'StripeProduct')

    # Feature limits mapping (from PLAN_LIMITS)
    PLAN_FEATURES = {
        'professional': {
            'events_per_month': 30,
            'certificates_per_month': 500,
            'max_attendees_per_event': 500,
        },
        'organization': {
            'events_per_month': None,  # Unlimited
            'certificates_per_month': None,  # Unlimited
            'max_attendees_per_event': 2000,
        },
    }

    for product in StripeProduct.objects.all():
        if product.plan in PLAN_FEATURES:
            limits = PLAN_FEATURES[product.plan]
            product.events_per_month = limits['events_per_month']
            product.certificates_per_month = limits['certificates_per_month']
            product.max_attendees_per_event = limits['max_attendees_per_event']
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_merge_20251229_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeproduct',
            name='show_contact_sales',
            field=models.BooleanField(default=False, help_text="If true, hides pricing and shows 'Contact Sales' button instead"),
        ),
        migrations.AddField(
            model_name='stripeproduct',
            name='events_per_month',
            field=models.PositiveIntegerField(blank=True, help_text='Max events per month (null = unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='stripeproduct',
            name='certificates_per_month',
            field=models.PositiveIntegerField(blank=True, help_text='Max certificates per month (null = unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='stripeproduct',
            name='max_attendees_per_event',
            field=models.PositiveIntegerField(blank=True, help_text='Max attendees per event (null = unlimited)', null=True),
        ),
        migrations.RunPython(populate_feature_limits, reverse_code=migrations.RunPython.noop),
    ]
