# Generated by Django 6.0 on 2025-12-29 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_add_contact_sales_and_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeprice',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='stripeproduct',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='stripeprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='stripeprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='stripeprice',
            name='uuid',
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True
            ),
        ),
        migrations.AlterField(
            model_name='stripeproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='stripeproduct',
            name='plan',
            field=models.CharField(
                choices=[
                    ('attendee', 'Attendee'),
                    ('professional', 'Professional'),
                    ('organization', 'Organization'),
                    ('starter', 'Starter'),
                    ('premium', 'Premium'),
                    ('organizer', 'Organizer'),
                ],
                help_text='Which subscription plan this product represents',
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='stripeproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='stripeproduct',
            name='uuid',
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True
            ),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(
                choices=[
                    ('attendee', 'Attendee'),
                    ('professional', 'Professional'),
                    ('organization', 'Organization'),
                    ('starter', 'Starter'),
                    ('premium', 'Premium'),
                    ('organizer', 'Organizer'),
                ],
                default='attendee',
                max_length=20,
            ),
        ),
    ]
