# Generated by Django 6.0.3 on 2026-04-05 21:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('egress_id', models.CharField(db_index=True, help_text="Provider's recording/egress ID", max_length=200, unique=True)),
                ('provider', models.CharField(default='livekit', max_length=50)),
                ('recording_start', models.DateTimeField(blank=True, null=True)),
                ('recording_end', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('processing', 'Processing'), ('available', 'Available'), ('error', 'Error'), ('deleted', 'Deleted')], default='recording', max_length=20)),
                ('storage_path', models.CharField(blank=True, help_text='Path to recording file (local or cloud)', max_length=500)),
                ('access_level', models.CharField(choices=[('registrants', 'Confirmed Registrants Only'), ('attendees', 'Attended Only'), ('certificate_holders', 'Certificate Holders Only'), ('public', 'Public (Anyone with Link)')], default='registrants', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('auto_publish', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('unique_viewers', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Video Recording',
                'verbose_name_plural': 'Video Recordings',
                'db_table': 'video_recordings',
                'ordering': ['-recording_start'],
            },
        ),
        migrations.CreateModel(
            name='VideoRecordingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('file_type', models.CharField(choices=[('video', 'Video (MP4)'), ('audio', 'Audio'), ('chat', 'Chat Log'), ('transcript', 'Transcript')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_extension', models.CharField(blank=True, max_length=10)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('storage_url', models.CharField(blank=True, help_text='URL or path to the file', max_length=500)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Video Recording File',
                'verbose_name_plural': 'Video Recording Files',
                'db_table': 'video_recording_files',
                'ordering': ['file_type'],
            },
        ),
        migrations.CreateModel(
            name='VideoRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('object_id', models.PositiveIntegerField()),
                ('room_id', models.CharField(db_index=True, help_text="Provider's room ID (e.g., LiveKit SID)", max_length=200)),
                ('room_name', models.CharField(db_index=True, help_text='Room name used for joining', max_length=200, unique=True)),
                ('provider', models.CharField(default='livekit', help_text='Video provider name', max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended'), ('error', 'Error')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Provider-agnostic room settings')),
                ('max_participants', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('error', models.TextField(blank=True)),
                ('error_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Video Room',
                'verbose_name_plural': 'Video Rooms',
                'db_table': 'video_rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('webhook_id', models.CharField(db_index=True, help_text="Provider's webhook delivery ID (deduplication)", max_length=200, unique=True)),
                ('event_type', models.CharField(choices=[('room_started', 'Room Started'), ('room_finished', 'Room Finished'), ('participant_joined', 'Participant Joined'), ('participant_left', 'Participant Left'), ('recording_started', 'Recording Started'), ('recording_ended', 'Recording Ended'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('event_timestamp', models.DateTimeField(help_text='When the event occurred (from provider)')),
                ('provider', models.CharField(default='livekit', max_length=50)),
                ('room_name', models.CharField(db_index=True, max_length=200)),
                ('room_id', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('attendance_records_created', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Video Webhook Log',
                'verbose_name_plural': 'Video Webhook Logs',
                'db_table': 'video_webhook_logs',
                'ordering': ['-event_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RecordingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('first_viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recording View',
                'verbose_name_plural': 'Recording Views',
                'db_table': 'video_recording_views',
            },
        ),
    ]
