# Generated by Django 6.0.3 on 2026-04-05 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferencing', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_recordings', to='events.event'),
        ),
        migrations.AddField(
            model_name='recordingview',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='conferencing.videorecording'),
        ),
        migrations.AddField(
            model_name='videorecordingfile',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='conferencing.videorecording'),
        ),
        migrations.AddField(
            model_name='videoroom',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='videorecording',
            name='video_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='conferencing.videoroom'),
        ),
        migrations.AddField(
            model_name='videowebhooklog',
            name='video_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='conferencing.videoroom'),
        ),
        migrations.AlterUniqueTogether(
            name='recordingview',
            unique_together={('recording', 'user')},
        ),
        migrations.AddIndex(
            model_name='videorecordingfile',
            index=models.Index(fields=['recording', 'file_type'], name='video_recor_recordi_5c7ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='videoroom',
            index=models.Index(fields=['content_type', 'object_id'], name='video_rooms_content_714014_idx'),
        ),
        migrations.AddIndex(
            model_name='videoroom',
            index=models.Index(fields=['room_name'], name='video_rooms_room_na_54f36b_idx'),
        ),
        migrations.AddIndex(
            model_name='videoroom',
            index=models.Index(fields=['room_id'], name='video_rooms_room_id_eee920_idx'),
        ),
        migrations.AddIndex(
            model_name='videoroom',
            index=models.Index(fields=['status'], name='video_rooms_status_96fd90_idx'),
        ),
        migrations.AddIndex(
            model_name='videorecording',
            index=models.Index(fields=['video_room'], name='video_recor_video_r_23e72f_idx'),
        ),
        migrations.AddIndex(
            model_name='videorecording',
            index=models.Index(fields=['egress_id'], name='video_recor_egress__e1d747_idx'),
        ),
        migrations.AddIndex(
            model_name='videorecording',
            index=models.Index(fields=['status'], name='video_recor_status_32618d_idx'),
        ),
        migrations.AddIndex(
            model_name='videorecording',
            index=models.Index(fields=['is_published', '-recording_start'], name='video_recor_is_publ_6fc4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='videowebhooklog',
            index=models.Index(fields=['event_type', '-event_timestamp'], name='video_webho_event_t_17f585_idx'),
        ),
        migrations.AddIndex(
            model_name='videowebhooklog',
            index=models.Index(fields=['room_name'], name='video_webho_room_na_ef5e63_idx'),
        ),
        migrations.AddIndex(
            model_name='videowebhooklog',
            index=models.Index(fields=['processing_status', '-created_at'], name='video_webho_process_7b9fed_idx'),
        ),
    ]
