# Generated by Django 6.0.3 on 2026-04-27 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('provider', models.CharField(help_text="STT provider used (e.g. 'deepgram', 'openai', 'assemblyai').", max_length=32)),
                ('provider_model', models.CharField(blank=True, help_text="Model identifier within the provider (e.g. 'nova-3').", max_length=64)),
                ('language_code', models.CharField(default='en-US', help_text='BCP-47 language code (e.g. en-US, fr-FR).', max_length=10)),
                ('status', models.CharField(choices=[('streaming', 'Streaming'), ('finalized', 'Finalized'), ('error', 'Error')], db_index=True, default='streaming', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('word_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('video_room', models.OneToOneField(help_text='The video session this transcript belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='conferencing.videoroom')),
            ],
            options={
                'db_table': 'transcripts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('start_ms', models.IntegerField(help_text='Start offset from recording start, in ms.')),
                ('end_ms', models.IntegerField(help_text='End offset from recording start, in ms.')),
                ('text', models.TextField()),
                ('is_final', models.BooleanField(default=True)),
                ('participant_identity', models.CharField(blank=True, db_index=True, max_length=255)),
                ('speaker_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('livekit_segment_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('source', models.CharField(choices=[('live', 'Live (streaming)'), ('edit', 'Organizer edit'), ('batch_repair', 'Post-event batch re-pass')], db_index=True, default='live', max_length=16)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='conferencing.transcriptsegment')),
                ('speaker_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_segments', to=settings.AUTH_USER_MODEL)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='conferencing.transcript')),
            ],
            options={
                'db_table': 'transcript_segments',
                'ordering': ['transcript_id', 'start_ms'],
                'indexes': [models.Index(fields=['transcript', 'start_ms'], name='transcript__transcr_b10094_idx'), models.Index(fields=['transcript', 'livekit_segment_id', 'source'], name='transcript__transcr_c204b6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source', 'live'), models.Q(('livekit_segment_id', ''), _negated=True)), fields=('transcript', 'livekit_segment_id', 'source'), name='one_live_segment_per_lk_id')],
            },
        ),
    ]
