# Generated by Django 6.0.3 on 2026-04-17 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencing', '0002_initial'),
        ('learning', '0005_coursesession_actual_end_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='course_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='learning.coursesession'),
        ),
    ]
