# Generated by Django 6.0.3 on 2026-04-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencing', '0004_transcript_segment_search_index'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='videoroom',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('content_type', 'object_id'), name='one_active_room_per_content'),
        ),
    ]
