# Generated by Django 6.0 on 2025-12-13 16:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import certificates.models
import common.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="When this record was last modified"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public identifier for external use",
                        unique=True,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("reason", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Certificate Status History",
                "verbose_name_plural": "Certificate Status Histories",
                "db_table": "certificate_status_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="When this record was last modified"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public identifier for external use",
                        unique=True,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this record was soft-deleted (null if active)",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (for organizer reference)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Template description", max_length=500),
                ),
                (
                    "file_url",
                    models.URLField(help_text="URL to template file in cloud storage"),
                ),
                (
                    "file_type",
                    models.CharField(
                        default="pdf",
                        help_text="File type (pdf, png, jpg)",
                        max_length=10,
                    ),
                ),
                (
                    "file_size_bytes",
                    models.PositiveIntegerField(default=0, help_text="File size in bytes"),
                ),
                (
                    "width_px",
                    models.PositiveIntegerField(
                        default=1056,
                        help_text="Template width in pixels (default: 11in @ 96dpi)",
                    ),
                ),
                (
                    "height_px",
                    models.PositiveIntegerField(
                        default=816,
                        help_text="Template height in pixels (default: 8.5in @ 96dpi)",
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[("landscape", "Landscape"), ("portrait", "Portrait")],
                        default="landscape",
                        help_text="Template orientation",
                        max_length=20,
                    ),
                ),
                (
                    "field_positions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Positions and styling for dynamic fields",
                        validators=[common.validators.validate_field_positions_schema],
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, help_text="Template version number"),
                ),
                (
                    "is_latest_version",
                    models.BooleanField(default=True, help_text="Is this the latest version"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="Default template for new events"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Available for selection (not archived)"),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of certificates issued with this template",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When last used to issue a certificate",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate Template",
                "verbose_name_plural": "Certificate Templates",
                "db_table": "certificate_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="When this record was last modified"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public identifier for external use",
                        unique=True,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this record was soft-deleted (null if active)",
                        null=True,
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(
                        db_index=True,
                        default=certificates.models.generate_verification_code,
                        help_text="Full verification code for URL",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        default=certificates.models.generate_short_code,
                        help_text="Short code displayed on certificate",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True)),
                (
                    "file_url",
                    models.URLField(blank=True, help_text="URL to generated PDF in cloud storage"),
                ),
                (
                    "file_generated_at",
                    models.DateTimeField(blank=True, help_text="When PDF was generated", null=True),
                ),
                (
                    "certificate_data",
                    models.JSONField(default=dict, help_text="Snapshot of data at time of issuance"),
                ),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "first_viewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="First time certificate was viewed",
                        null=True,
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "first_downloaded_at",
                    models.DateTimeField(blank=True, help_text="First time PDF was downloaded", null=True),
                ),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "issued_by",
                    models.ForeignKey(
                        help_text="User who issued the certificate",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificates_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "db_table": "certificates",
                "ordering": ["-created_at"],
            },
        ),
    ]
