# Generated by Django 6.0 on 2025-12-13 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("certificates", "0001_initial"),
        ("registrations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="registration",
            field=models.OneToOneField(
                help_text="Registration this certificate was issued for",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certificate",
                to="registrations.registration",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificates_revoked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="certificatestatushistory",
            name="certificate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="certificates.certificate",
            ),
        ),
        migrations.AddField(
            model_name="certificatestatushistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="original_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Original template this is a version of",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="certificates.certificatetemplate",
            ),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="owner",
            field=models.ForeignKey(
                help_text="Organizer who owns this template",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certificate_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="template",
            field=models.ForeignKey(
                help_text="Template used to generate certificate",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certificates",
                to="certificates.certificatetemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="certificatetemplate",
            index=models.Index(fields=["owner"], name="certificate_owner_i_b9c49a_idx"),
        ),
        migrations.AddIndex(
            model_name="certificatetemplate",
            index=models.Index(
                fields=["owner", "is_active"], name="certificate_owner_i_e1234c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificatetemplate",
            index=models.Index(fields=["uuid"], name="certificate_uuid_a2f8cf_idx"),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["verification_code"], name="certificate_verific_8df4b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["short_code"], name="certificate_short_c_6c3728_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["status"], name="certificate_status_a01db5_idx"),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["uuid"], name="certificate_uuid_cde354_idx"),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["issued_by", "-created_at"],
                name="certificate_issued__16756f_idx",
            ),
        ),
    ]
