# Generated by Django 6.0 on 2025-12-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='qrcode',
            field=models.ImageField(blank=True, help_text='QR code image', null=True, upload_to='certificates/qrcodes/'),
        ),
    ]
