# Generated by Django 6.0.3 on 2026-04-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='is_latest_version',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='original_template',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='version',
        ),
    ]
