# Generated by Django 6.0.3 on 2026-04-11 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_remove_certificatetemplate_is_latest_version_and_more'),
        ('learning', '0002_coursestaff'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('registration__isnull', False), ('status', 'active')), fields=('registration',), name='unique_active_cert_per_registration'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(condition=models.Q(('course_enrollment__isnull', False), ('deleted_at__isnull', True), ('status', 'active')), fields=('course_enrollment',), name='unique_active_cert_per_course_enrollment'),
        ),
    ]
