# Generated by Django 6.0 on 2025-12-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='file_url',
            field=models.URLField(blank=True, help_text='URL to template file in cloud storage'),
        ),
    ]
