# Generated by Django 6.0.3 on 2026-04-11 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_certificate_unique_active_cert_per_registration_and_more'),
        ('learning', '0002_coursestaff'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='course_enrollment',
            field=models.ForeignKey(blank=True, help_text='Course enrollment this certificate was issued for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='learning.courseenrollment'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='registration',
            field=models.ForeignKey(blank=True, help_text='Registration this certificate was issued for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='registrations.registration'),
        ),
    ]
