# Generated by Django 6.0 on 2025-12-22 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_allow_blank_file_url'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                help_text='Organization that owns this template (null for individual organizers)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='certificate_templates',
                to='organizations.organization',
            ),
        ),
    ]
