# Generated by Django 6.0 on 2025-12-22 04:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_certificatetemplate_organization'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='is_shared',
            field=models.BooleanField(
                default=False, help_text='If True, this org template is available to all org members for their events'
            ),
        ),
        migrations.AddIndex(
            model_name='certificatetemplate',
            index=models.Index(fields=['organization', 'is_shared'], name='certificate_organiz_ad0ec8_idx'),
        ),
    ]
