# Generated by Django 6.0 on 2025-12-22 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_certificatetemplate_is_shared_and_more'),
        ('learning', '0001_initial'),
        ('registrations', '0002_registration_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='course_enrollment',
            field=models.OneToOneField(blank=True, help_text='Course enrollment this certificate was issued for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='learning.courseenrollment'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='registration',
            field=models.OneToOneField(blank=True, help_text='Registration this certificate was issued for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='registrations.registration'),
        ),
    ]
