# Generated by Django 6.0.3 on 2026-04-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, help_text='Stripe Coupon id created for this promo code', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='stripe_promotion_code_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Promotion Code id (promo_...); redeemed at checkout', max_length=64, null=True, unique=True),
        ),
    ]
