# Generated by Django 6.0 on 2025-12-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='promocode',
            new_name='promo_codes_owner_i_4ee98e_idx',
            old_name='promo_codes_owner_i_c2b5d3_idx',
        ),
        migrations.RenameIndex(
            model_name='promocode',
            new_name='promo_codes_code_5b1d05_idx',
            old_name='promo_codes_code_e5a7b1_idx',
        ),
        migrations.RenameIndex(
            model_name='promocodeusage',
            new_name='promo_code__promo_c_4106d3_idx',
            old_name='promo_code__promo_c_a1c2d3_idx',
        ),
        migrations.RenameIndex(
            model_name='promocodeusage',
            new_name='promo_code__registr_a4cb9f_idx',
            old_name='promo_code__registr_b2c3d4_idx',
        ),
    ]
