# Generated by Django 6.0.3 on 2026-04-24 04:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0002_promocode_stripe_coupon_id_and_more'),
        ('registrations', '0004_remove_registration_billing_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='promocodeusage',
            constraint=models.UniqueConstraint(fields=('registration', 'promo_code'), name='uniq_promo_usage_per_registration_code'),
        ),
    ]
