# Generated by Django 6.0 on 2026-01-16 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, db_index=True, help_text='When this record was soft-deleted (null if active)', null=True
                    ),
                ),
                ('name', models.CharField(help_text='Organization display name', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='About this organization', max_length=2000)),
                (
                    'logo',
                    models.ImageField(blank=True, help_text='Organization logo', null=True, upload_to='organizations/logos/'),
                ),
                ('logo_url', models.URLField(blank=True, help_text='External logo URL (if not uploaded)')),
                ('website', models.URLField(blank=True, help_text='Organization website')),
                ('primary_color', models.CharField(default='#0066CC', help_text='Primary brand color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#004499', help_text='Secondary brand color (hex)', max_length=7)),
                ('contact_email', models.EmailField(blank=True, help_text='Public contact email', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Public contact phone', max_length=20)),
                (
                    'gst_hst_number',
                    models.CharField(blank=True, help_text='GST/HST registration number for tax handling', max_length=50),
                ),
                ('is_active', models.BooleanField(default=True, help_text='Whether organization is active')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether organization is verified')),
                ('is_public', models.BooleanField(default=True, help_text='Whether organization is visible publicly')),
                (
                    'stripe_connect_id',
                    models.CharField(blank=True, help_text='Stripe Connect Account ID', max_length=255, null=True),
                ),
                (
                    'stripe_account_status',
                    models.CharField(default='pending', help_text='Connect account status', max_length=50),
                ),
                ('stripe_charges_enabled', models.BooleanField(default=False, help_text='Whether account can accept payments')),
                ('members_count', models.PositiveIntegerField(default=0, help_text='Number of active members')),
                ('events_count', models.PositiveIntegerField(default=0, help_text='Number of events')),
                ('courses_count', models.PositiveIntegerField(default=0, help_text='Number of courses')),
                (
                    'onboarding_completed',
                    models.BooleanField(default=False, help_text='Whether organization completed initial onboarding'),
                ),
                (
                    'onboarding_completed_at',
                    models.DateTimeField(blank=True, help_text='When onboarding was completed', null=True),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        help_text='User who created this organization',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_organizations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('admin', 'Admin'),
                            ('organizer', 'Organizer'),
                            ('course_manager', 'Course Manager'),
                            ('instructor', 'Instructor'),
                        ],
                        default='organizer',
                        help_text='Role within organization',
                        max_length=20,
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        blank=True, help_text='Job title in organization (e.g., Training Manager)', max_length=100
                    ),
                ),
                ('is_active', models.BooleanField(default=True, help_text='Whether membership is active')),
                ('invited_at', models.DateTimeField(blank=True, help_text='When invitation was sent', null=True)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When invitation was accepted', null=True)),
                (
                    'invitation_token',
                    models.CharField(blank=True, db_index=True, help_text='Token for accepting invitation', max_length=64),
                ),
                (
                    'invitation_email',
                    models.EmailField(blank=True, help_text='Email address invitation was sent to', max_length=254),
                ),
                (
                    'linked_from_individual',
                    models.BooleanField(default=False, help_text='Whether user was linked from individual organizer account'),
                ),
                (
                    'linked_at',
                    models.DateTimeField(blank=True, help_text="When user's data was linked to organization", null=True),
                ),
                (
                    'organizer_billing_payer',
                    models.CharField(
                        blank=True,
                        choices=[('organization', 'Organization Pays'), ('organizer', 'Organizer Pays')],
                        help_text='Who pays for organizer subscription (only for organizer role)',
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    'stripe_subscription_item_id',
                    models.CharField(
                        blank=True, help_text='Stripe subscription item ID if org pays for organizer', max_length=255
                    ),
                ),
                (
                    'assigned_course',
                    models.ForeignKey(
                        blank=True,
                        help_text='Course the instructor is assigned to (instructors can only access their assigned course)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='assigned_instructors',
                        to='learning.course',
                    ),
                ),
                (
                    'invited_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='sent_org_invites',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'linked_subscription',
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to organizer's individual subscription if organizer pays",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='organization_memberships',
                        to='billing.subscription',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='organization_memberships',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Organization Membership',
                'verbose_name_plural': 'Organization Memberships',
                'db_table': 'organization_memberships',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('plan', models.CharField(choices=[('organization', 'Organization')], default='organization', max_length=20)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('trialing', 'Trialing'),
                            ('past_due', 'Past Due'),
                            ('canceled', 'Canceled'),
                            ('unpaid', 'Unpaid'),
                        ],
                        default='trialing',
                        max_length=20,
                    ),
                ),
                ('included_seats', models.PositiveIntegerField(default=1, help_text='Seats included in base plan')),
                ('additional_seats', models.PositiveIntegerField(default=0, help_text='Extra seats purchased')),
                ('seat_price_cents', models.PositiveIntegerField(default=0, help_text='Price per additional seat in cents')),
                ('active_organizer_seats', models.PositiveIntegerField(default=1, help_text='Current organizer seats in use')),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('events_created_this_period', models.PositiveIntegerField(default=0)),
                ('courses_created_this_period', models.PositiveIntegerField(default=0)),
                (
                    'organization',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscription',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Organization Subscription',
                'verbose_name_plural': 'Organization Subscriptions',
                'db_table': 'organization_subscriptions',
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='organizatio_slug_5b8b37_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_bdc355_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_by'], name='organizatio_created_7b4623_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'role'], name='organizatio_organiz_25ae86_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user', 'is_active'], name='organizatio_user_id_c5f3a8_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['invitation_token'], name='organizatio_invitat_b745fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together={('organization', 'user')},
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['plan'], name='organizatio_plan_1d416e_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['status'], name='organizatio_status_ed28b0_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['current_period_end'], name='organizatio_current_27561c_idx'),
        ),
    ]
