# Generated by Django 6.0 on 2025-12-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stripe_account_status',
            field=models.CharField(default='pending', help_text='Connect account status', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False, help_text='Whether account can accept payments'),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_connect_id',
            field=models.CharField(blank=True, help_text='Stripe Connect Account ID', max_length=255, null=True),
        ),
    ]
