# Generated by Django 6.0 on 2026-01-07 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_stripeproduct_grace_period_days'),
        ('organizations', '0003_add_gst_hst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='linked_subscription',
            field=models.ForeignKey(
                blank=True,
                help_text="Link to organizer's individual subscription if organizer pays",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='organization_memberships',
                to='billing.subscription',
            ),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='organizer_billing_payer',
            field=models.CharField(
                blank=True,
                choices=[('organization', 'Organization Pays'), ('organizer', 'Organizer Pays')],
                help_text='Who pays for organizer subscription (only for organizer role)',
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='stripe_subscription_item_id',
            field=models.CharField(
                blank=True, help_text='Stripe subscription item ID if org pays for organizer', max_length=255
            ),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(
                choices=[
                    ('admin', 'Admin'),
                    ('organizer', 'Organizer'),
                    ('course_manager', 'Course Manager'),
                    ('instructor', 'Instructor'),
                ],
                default='organizer',
                help_text='Role within organization',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='plan',
            field=models.CharField(
                choices=[('organization', 'Organization')],
                default='organization',
                max_length=20,
            ),
        ),
    ]
