# Generated by Django 6.0 on 2026-01-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_update_organization_roles_and_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(
                choices=[
                    ('admin', 'Admin'),
                    ('organizer', 'Organizer'),
                    ('course_manager', 'Course Manager'),
                    ('instructor', 'Instructor'),
                ],
                default='organizer',
                help_text='Role within organization',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='plan',
            field=models.CharField(choices=[('organization', 'Organization')], default='organization', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='status',
            field=models.CharField(
                choices=[
                    ('active', 'Active'),
                    ('trialing', 'Trialing'),
                    ('past_due', 'Past Due'),
                    ('canceled', 'Canceled'),
                    ('unpaid', 'Unpaid'),
                ],
                default='trialing',
                max_length=20,
            ),
        ),
    ]
