# Generated by Django 6.0 on 2026-01-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_add_organization_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether organization completed initial onboarding'),
        ),
        migrations.AddField(
            model_name='organization',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, help_text='When onboarding was completed', null=True),
        ),
    ]
