# Generated by Django 6.0 on 2026-01-01 21:43

import common.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                (
                    'email',
                    common.fields.LowercaseEmailField(
                        db_index=True, help_text='Contact email (canonical, lowercase)', max_length=254
                    ),
                ),
                ('full_name', models.CharField(help_text='Full name', max_length=255)),
                ('professional_title', models.CharField(blank=True, help_text='Professional title', max_length=255)),
                ('organization_name', models.CharField(blank=True, help_text='Organization/company', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Private notes about contact', max_length=2000)),
                (
                    'source',
                    models.CharField(blank=True, help_text='How contact was added (manual, csv, registration)', max_length=50),
                ),
                ('events_invited_count', models.PositiveIntegerField(default=0, help_text='Number of events invited to')),
                ('events_attended_count', models.PositiveIntegerField(default=0, help_text='Number of events attended')),
                ('last_invited_at', models.DateTimeField(blank=True, null=True)),
                ('last_attended_at', models.DateTimeField(blank=True, null=True)),
                ('email_opted_out', models.BooleanField(default=False, help_text='Contact has opted out of emails')),
                ('email_bounced', models.BooleanField(default=False, help_text='Email has bounced')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('name', models.CharField(help_text='List name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='List description', max_length=500)),
                ('is_default', models.BooleanField(default=False, help_text='Default list for new contacts')),
                ('contact_count', models.PositiveIntegerField(default=0, help_text='Denormalized: number of contacts in list')),
            ],
            options={
                'verbose_name': 'Contact List',
                'verbose_name_plural': 'Contact Lists',
                'db_table': 'contact_lists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('name', models.CharField(help_text='Tag name', max_length=50)),
                ('color', models.CharField(default='#6B7280', help_text='Hex color for display', max_length=7)),
                ('description', models.CharField(blank=True, help_text='Tag description', max_length=200)),
                ('contact_count', models.PositiveIntegerField(default=0, help_text='Number of contacts with this tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
    ]
