# Generated by Django 6.0 on 2026-01-16 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='added_from_event',
            field=models.ForeignKey(
                blank=True,
                help_text='Event this contact was added from (if applicable)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='events.event',
            ),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(
                blank=True,
                help_text="Linked user account (if they've signed up)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='contact_records',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
