# Generated by Django 6.0 on 2026-01-19 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='added_from_event',
            field=models.ForeignKey(
                blank=True,
                help_text='Event this contact was added from (if applicable)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='events.event',
            ),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(
                blank=True,
                help_text="Linked user account (if they've signed up)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='contact_records',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='owner',
            field=models.ForeignKey(
                help_text='User who created this list',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='contact_lists',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_list',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.contactlist'
            ),
        ),
        migrations.AddField(
            model_name='tag',
            name='owner',
            field=models.ForeignKey(
                help_text='User who created this tag',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tags',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='contacts.tag'),
        ),
        migrations.AddIndex(
            model_name='contactlist',
            index=models.Index(fields=['owner'], name='contact_lis_owner_i_77b5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='contactlist',
            index=models.Index(fields=['uuid'], name='contact_lis_uuid_f044b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactlist',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_personal_contact_list_name'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['owner'], name='tags_owner_i_f436b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_personal_tag_name'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['contact_list'], name='contacts_contact_ca9e63_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='contacts_email_2eb381_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['user'], name='contacts_user_id_502575_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['uuid'], name='contacts_uuid_102d8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('contact_list', 'email')},
        ),
    ]
