# Generated by Django 6.0 on 2026-01-07 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
        ('organizations', '0003_add_gst_hst_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactlist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                help_text='If set, list is shared with all org members',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='contact_lists',
                to='organizations.organization',
            ),
        ),
        migrations.AddField(
            model_name='tag',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                help_text='If set, tag is shared with all org members',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tags',
                to='organizations.organization',
            ),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='owner',
            field=models.ForeignKey(
                help_text='User who created this list',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='contact_lists',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='owner',
            field=models.ForeignKey(
                help_text='User who created this tag',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tags',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='contactlist',
            index=models.Index(fields=['organization'], name='contact_lis_organiz_9ac457_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['organization'], name='tags_organiz_38f7d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactlist',
            constraint=models.UniqueConstraint(
                condition=models.Q(('organization__isnull', True)),
                fields=('owner', 'name'),
                name='unique_personal_contact_list_name',
            ),
        ),
        migrations.AddConstraint(
            model_name='contactlist',
            constraint=models.UniqueConstraint(
                condition=models.Q(('organization__isnull', False)),
                fields=('organization', 'name'),
                name='unique_org_contact_list_name',
            ),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(
                condition=models.Q(('organization__isnull', True)), fields=('owner', 'name'), name='unique_personal_tag_name'
            ),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(
                condition=models.Q(('organization__isnull', False)), fields=('organization', 'name'), name='unique_org_tag_name'
            ),
        ),
        migrations.RemoveField(
            model_name='contactlist',
            name='is_default',
        ),
    ]
