# Generated by Django 6.0.3 on 2026-04-27 02:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('events', '0002_initial'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('email_type', models.CharField(choices=[('verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('event_reminder', 'Event Reminder'), ('registration_confirm', 'Registration Confirmation'), ('certificate', 'Certificate Delivery'), ('invitation', 'Event Invitation'), ('event_update', 'Event Update'), ('waitlist_promotion', 'Waitlist Promotion'), ('course_session_reminder', 'Course Session Reminder'), ('course_session_update', 'Course Session Update')], db_index=True, max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, help_text='Message ID from email provider', max_length=100)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='certificates.certificate')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='events.event')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_received', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='registrations.registration')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('template_key', models.CharField(db_index=True, max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('send_at', models.DateTimeField(db_index=True)),
                ('batch_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_sources', to='integrations.emaillog')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_emails', to='events.event')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_emails', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_emails', to='registrations.registration')),
            ],
            options={
                'db_table': 'scheduled_emails',
                'ordering': ['send_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient_email'], name='email_logs_recipie_00ae8d_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['email_type', '-created_at'], name='email_logs_email_t_6d62ae_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', '-created_at'], name='email_logs_status_012124_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['event'], name='email_logs_event_i_b3d2ce_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledemail',
            index=models.Index(fields=['status', 'send_at'], name='scheduled_e_status_38fe81_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledemail',
            index=models.Index(fields=['batch_key'], name='scheduled_e_batch_k_47bae2_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledemail',
            index=models.Index(fields=['event', 'template_key'], name='scheduled_e_event_i_80a183_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduledemail',
            constraint=models.UniqueConstraint(fields=('event', 'recipient_email', 'template_key', 'send_at'), name='uniq_scheduled_email_per_event_recipient_template_time'),
        ),
    ]
