# Generated by Django 6.0 on 2026-01-19 06:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('events', '0002_initial'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('zoom_meeting_id', models.CharField(db_index=True, help_text='Zoom meeting ID', max_length=20)),
                ('zoom_meeting_uuid', models.CharField(help_text='Zoom meeting UUID (unique per instance)', max_length=100)),
                (
                    'zoom_recording_id',
                    models.CharField(db_index=True, help_text="Zoom's recording ID", max_length=100, unique=True),
                ),
                ('topic', models.CharField(blank=True, help_text='Meeting topic from Zoom', max_length=300)),
                ('recording_start', models.DateTimeField(help_text='When recording started')),
                ('recording_end', models.DateTimeField(help_text='When recording ended')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Recording duration in seconds')),
                ('total_size_bytes', models.BigIntegerField(default=0, help_text='Total size of all recording files')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('processing', 'Processing'),
                            ('available', 'Available'),
                            ('expired', 'Expired'),
                            ('deleted', 'Deleted'),
                            ('error', 'Error'),
                        ],
                        default='processing',
                        max_length=20,
                    ),
                ),
                ('zoom_expires_at', models.DateTimeField(blank=True, help_text='When recording expires on Zoom', null=True)),
                (
                    'access_level',
                    models.CharField(
                        choices=[
                            ('registrants', 'Confirmed Registrants Only'),
                            ('attendees', 'Attended Only'),
                            ('certificate_holders', 'Certificate Holders Only'),
                            ('public', 'Public (Anyone with Link)'),
                        ],
                        default='registrants',
                        max_length=20,
                    ),
                ),
                ('zoom_password', models.CharField(blank=True, help_text='Password for Zoom share URL', max_length=50)),
                (
                    'access_password',
                    models.CharField(blank=True, help_text='Optional platform password for access', max_length=50),
                ),
                ('title', models.CharField(blank=True, help_text='Display title (defaults to event title)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description shown to viewers', max_length=2000)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Custom thumbnail image URL')),
                ('is_published', models.BooleanField(default=False, help_text='Whether recording is visible to attendees')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('auto_publish', models.BooleanField(default=False, help_text='Automatically publish when available')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('unique_viewers', models.PositiveIntegerField(default=0)),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='events.event'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Zoom Recording',
                'verbose_name_plural': 'Zoom Recordings',
                'db_table': 'zoom_recordings',
                'ordering': ['-recording_start'],
            },
        ),
        migrations.CreateModel(
            name='RecordingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('first_viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=1)),
                (
                    'registration',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='recording_views',
                        to='registrations.registration',
                    ),
                ),
                (
                    'recording',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='views', to='integrations.zoomrecording'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Recording View',
                'verbose_name_plural': 'Recording Views',
                'db_table': 'recording_views',
            },
        ),
        migrations.CreateModel(
            name='ZoomRecordingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('zoom_file_id', models.CharField(help_text="Zoom's file ID", max_length=100)),
                (
                    'file_type',
                    models.CharField(
                        choices=[
                            ('video', 'Video (MP4)'),
                            ('audio', 'Audio (M4A)'),
                            ('chat', 'Chat Log (TXT)'),
                            ('transcript', 'Transcript (VTT)'),
                            ('timeline', 'Timeline (JSON)'),
                            ('cc', 'Closed Captions (VTT)'),
                            ('summary', 'AI Summary'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'recording_type',
                    models.CharField(
                        blank=True, help_text='E.g., shared_screen_with_speaker_view, gallery_view', max_length=50
                    ),
                ),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_extension', models.CharField(blank=True, max_length=10)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('download_url', models.URLField(blank=True, help_text='Zoom download URL', max_length=2000)),
                ('play_url', models.URLField(blank=True, help_text='Zoom play URL (for embedding)', max_length=2000)),
                ('share_url', models.URLField(blank=True, help_text='Shareable URL', max_length=2000)),
                (
                    'storage_url',
                    models.URLField(blank=True, help_text='Our storage URL (if file is copied locally)', max_length=500),
                ),
                ('processing_status', models.CharField(default='completed', help_text='Zoom processing status', max_length=20)),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this file is shown to viewers')),
                (
                    'recording',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='files', to='integrations.zoomrecording'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Zoom Recording File',
                'verbose_name_plural': 'Zoom Recording Files',
                'db_table': 'zoom_recording_files',
                'ordering': ['file_type', 'recording_type'],
            },
        ),
        migrations.CreateModel(
            name='ZoomWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                (
                    'webhook_id',
                    models.CharField(
                        db_index=True, help_text="Zoom's webhook delivery ID (for deduplication)", max_length=100, unique=True
                    ),
                ),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('meeting.started', 'Meeting Started'),
                            ('meeting.ended', 'Meeting Ended'),
                            ('meeting.participant_joined', 'Participant Joined'),
                            ('meeting.participant_left', 'Participant Left'),
                            ('meeting.participant_joined_waiting_room', 'Participant Waiting'),
                            ('webinar.started', 'Webinar Started'),
                            ('webinar.ended', 'Webinar Ended'),
                            ('recording.completed', 'Recording Completed'),
                            ('other', 'Other'),
                        ],
                        db_index=True,
                        default='other',
                        max_length=50,
                    ),
                ),
                ('event_timestamp', models.DateTimeField(help_text='When event occurred (from Zoom)')),
                ('zoom_meeting_id', models.CharField(db_index=True, help_text='Zoom meeting ID', max_length=20)),
                (
                    'zoom_meeting_uuid',
                    models.CharField(blank=True, help_text='Zoom meeting UUID (unique per instance)', max_length=100),
                ),
                ('payload', models.JSONField(default=dict, help_text='Full webhook payload')),
                ('headers', models.JSONField(default=dict, help_text='Request headers (for debugging)')),
                (
                    'processing_status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('processing', 'Processing'),
                            ('completed', 'Completed'),
                            ('failed', 'Failed'),
                            ('skipped', 'Skipped'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('processed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('processing_attempts', models.PositiveIntegerField(default=0, help_text='Number of processing attempts')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('error_traceback', models.TextField(blank=True, help_text='Full traceback for debugging')),
                (
                    'attendance_records_created',
                    models.PositiveIntegerField(default=0, help_text='Number of attendance records created'),
                ),
                (
                    'event',
                    models.ForeignKey(
                        blank=True,
                        help_text='Matched platform event',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='zoom_webhooks',
                        to='events.event',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Zoom Webhook Log',
                'verbose_name_plural': 'Zoom Webhook Logs',
                'db_table': 'zoom_webhook_logs',
                'ordering': ['-event_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                (
                    'email_type',
                    models.CharField(
                        choices=[
                            ('verification', 'Email Verification'),
                            ('password_reset', 'Password Reset'),
                            ('event_reminder', 'Event Reminder'),
                            ('registration_confirm', 'Registration Confirmation'),
                            ('certificate', 'Certificate Delivery'),
                            ('invitation', 'Event Invitation'),
                            ('event_update', 'Event Update'),
                            ('waitlist_promotion', 'Waitlist Promotion'),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ('subject', models.CharField(max_length=255)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('sent', 'Sent'),
                            ('delivered', 'Delivered'),
                            ('opened', 'Opened'),
                            ('clicked', 'Clicked'),
                            ('bounced', 'Bounced'),
                            ('failed', 'Failed'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                (
                    'provider_message_id',
                    models.CharField(blank=True, help_text='Message ID from email provider', max_length=100),
                ),
                (
                    'certificate',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='emails',
                        to='certificates.certificate',
                    ),
                ),
                (
                    'event',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='emails',
                        to='events.event',
                    ),
                ),
                (
                    'recipient_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='emails_received',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'registration',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='emails',
                        to='registrations.registration',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['recipient_email'], name='email_logs_recipie_00ae8d_idx'),
                    models.Index(fields=['email_type', '-created_at'], name='email_logs_email_t_6d62ae_idx'),
                    models.Index(fields=['status', '-created_at'], name='email_logs_status_012124_idx'),
                    models.Index(fields=['event'], name='email_logs_event_i_b3d2ce_idx'),
                ],
            },
        ),
        migrations.AddIndex(
            model_name='zoomrecording',
            index=models.Index(fields=['event'], name='zoom_record_event_i_51e7d4_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomrecording',
            index=models.Index(fields=['zoom_recording_id'], name='zoom_record_zoom_re_8fecfd_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomrecording',
            index=models.Index(fields=['zoom_meeting_id'], name='zoom_record_zoom_me_11f00f_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomrecording',
            index=models.Index(fields=['status'], name='zoom_record_status_b441e3_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomrecording',
            index=models.Index(fields=['is_published', '-recording_start'], name='zoom_record_is_publ_bde77c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recordingview',
            unique_together={('recording', 'registration')},
        ),
        migrations.AddIndex(
            model_name='zoomrecordingfile',
            index=models.Index(fields=['recording', 'file_type'], name='zoom_record_recordi_00564b_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomrecordingfile',
            index=models.Index(fields=['zoom_file_id'], name='zoom_record_zoom_fi_52e8c7_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebhooklog',
            index=models.Index(fields=['webhook_id'], name='zoom_webhoo_webhook_89f681_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebhooklog',
            index=models.Index(fields=['event_type', '-event_timestamp'], name='zoom_webhoo_event_t_2ab94b_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebhooklog',
            index=models.Index(fields=['zoom_meeting_id'], name='zoom_webhoo_zoom_me_6b26d2_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebhooklog',
            index=models.Index(fields=['processing_status', '-created_at'], name='zoom_webhoo_process_ec8a08_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebhooklog',
            index=models.Index(fields=['event', '-event_timestamp'], name='zoom_webhoo_event_i_c0dbc9_idx'),
        ),
        migrations.AddIndex(
            model_name='zoomwebhooklog',
            index=models.Index(fields=['-created_at'], name='zoom_webhoo_created_d1aee2_idx'),
        ),
    ]
