# Generated by Django 6.0.3 on 2026-04-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('event_reminder', 'Event Reminder'), ('registration_confirm', 'Registration Confirmation'), ('certificate', 'Certificate Delivery'), ('invitation', 'Event Invitation'), ('event_update', 'Event Update'), ('waitlist_promotion', 'Waitlist Promotion'), ('course_session_reminder', 'Course Session Reminder'), ('course_session_update', 'Course Session Update')], db_index=True, max_length=30),
        ),
    ]
