# Generated by Django 6.0.3 on 2026-04-19 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_event_type'),
        ('integrations', '0002_alter_emaillog_email_type'),
        ('registrations', '0002_rename_attendance_zoom_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('template_key', models.CharField(db_index=True, max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('send_at', models.DateTimeField(db_index=True)),
                ('batch_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_sources', to='integrations.emaillog')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_emails', to='events.event')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_emails', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_emails', to='registrations.registration')),
            ],
            options={
                'db_table': 'scheduled_emails',
                'ordering': ['send_at'],
                'indexes': [models.Index(fields=['status', 'send_at'], name='scheduled_e_status_38fe81_idx'), models.Index(fields=['batch_key'], name='scheduled_e_batch_k_47bae2_idx')],
            },
        ),
    ]
