# Generated by Django 6.0.3 on 2026-04-25 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_reminder_offsets_minutes'),
        ('integrations', '0003_scheduledemail'),
        ('registrations', '0004_remove_registration_billing_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scheduledemail',
            index=models.Index(fields=['event', 'template_key'], name='scheduled_e_event_i_80a183_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduledemail',
            constraint=models.UniqueConstraint(fields=('event', 'recipient_email', 'template_key', 'send_at'), name='uniq_scheduled_email_per_event_recipient_template_time'),
        ),
    ]
