# Generated by Django 6.0.3 on 2026-04-27 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('is_anonymous', models.BooleanField(default=False, help_text='If true, hide attendee identity from organizer')),
                ('event', models.ForeignKey(help_text='Event being evaluated', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='events.event')),
                ('registration', models.ForeignKey(help_text='Registration record of the attendee providing feedback', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='registrations.registration')),
                ('session', models.ForeignKey(blank=True, help_text='Session being evaluated; null for event-level feedback', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='events.eventsession')),
            ],
            options={
                'verbose_name': 'Event Feedback',
                'verbose_name_plural': 'Event Feedback',
                'db_table': 'event_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('label', models.CharField(help_text='Question label', max_length=200)),
                ('field_type', models.CharField(choices=[('rating', 'Rating (1-5)'), ('text', 'Single Line Text'), ('textarea', 'Multi-line Text'), ('select', 'Dropdown'), ('multiselect', 'Multi-select'), ('checkbox', 'Yes/No Checkbox'), ('radio', 'Radio Buttons'), ('date', 'Date'), ('number', 'Number')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('options', models.JSONField(blank=True, default=list, help_text='Choice list for select / multiselect / radio fields')),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_fields', to='events.event')),
            ],
            options={
                'verbose_name': 'Feedback Field',
                'verbose_name_plural': 'Feedback Fields',
                'db_table': 'feedback_fields',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackFieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('value', models.JSONField(blank=True, help_text='Answer (type depends on field.field_type)', null=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_responses', to='feedback.eventfeedback')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.feedbackfield')),
            ],
            options={
                'verbose_name': 'Feedback Field Response',
                'verbose_name_plural': 'Feedback Field Responses',
                'db_table': 'feedback_field_responses',
                'ordering': ['field__order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventfeedback',
            constraint=models.UniqueConstraint(fields=('event', 'session', 'registration'), name='unique_feedback_per_session_registration'),
        ),
        migrations.AddConstraint(
            model_name='feedbackfieldresponse',
            constraint=models.UniqueConstraint(fields=('feedback', 'field'), name='unique_response_per_field'),
        ),
    ]
