# Generated by Django 6.0 on 2026-01-16 21:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                (
                    'rating',
                    models.PositiveIntegerField(
                        help_text='Overall event rating (1-5)',
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
                    ),
                ),
                (
                    'content_quality_rating',
                    models.PositiveIntegerField(
                        help_text='Rating of content quality and relevance (1-5)',
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
                    ),
                ),
                (
                    'speaker_rating',
                    models.PositiveIntegerField(
                        help_text='Rating of speaker effectiveness (1-5)',
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
                    ),
                ),
                ('comments', models.TextField(blank=True, help_text='General comments and suggestions')),
                (
                    'is_anonymous',
                    models.BooleanField(default=False, help_text='If true, hide attendee identity from organizer'),
                ),
                (
                    'event',
                    models.ForeignKey(
                        help_text='Event being evaluated',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feedback',
                        to='events.event',
                    ),
                ),
                (
                    'registration',
                    models.ForeignKey(
                        help_text='Registration record of the attendee providing feedback',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feedback',
                        to='registrations.registration',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Event Feedback',
                'verbose_name_plural': 'Event Feedback',
                'db_table': 'event_feedback',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'registration')},
            },
        ),
    ]
