# Generated by Django 6.0 on 2025-12-13 16:20

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="When this record was last modified"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public identifier for external use",
                        unique=True,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this record was soft-deleted (null if active)",
                        null=True,
                    ),
                ),
                (
                    "email",
                    common.fields.LowercaseEmailField(
                        db_index=True,
                        help_text="Primary email address (used for login)",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full name",
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "professional_title",
                    models.CharField(
                        blank=True,
                        help_text="Professional title (e.g., MD, PhD)",
                        max_length=255,
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True,
                        help_text="Organization/company name",
                        max_length=255,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="User's preferred timezone",
                        max_length=50,
                    ),
                ),
                (
                    "profile_photo_url",
                    models.URLField(blank=True, help_text="URL to profile photo"),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("attendee", "Attendee"), ("organizer", "Organizer")],
                        db_index=True,
                        default="attendee",
                        help_text="Account type determines available features",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether user can log in"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, help_text="Can access admin site"),
                ),
                (
                    "email_verified",
                    models.BooleanField(default=False, help_text="Whether email has been verified"),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(blank=True, help_text="When email was verified", null=True),
                ),
                (
                    "email_verification_token",
                    models.CharField(
                        blank=True,
                        help_text="Token for email verification",
                        max_length=100,
                    ),
                ),
                (
                    "email_verification_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When verification email was sent",
                        null=True,
                    ),
                ),
                (
                    "password_reset_token",
                    models.CharField(blank=True, help_text="Token for password reset", max_length=100),
                ),
                (
                    "password_reset_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When password reset was requested",
                        null=True,
                    ),
                ),
                (
                    "notify_event_reminders",
                    models.BooleanField(default=True, help_text="Receive event reminders"),
                ),
                (
                    "notify_certificate_issued",
                    models.BooleanField(default=True, help_text="Receive certificate notifications"),
                ),
                (
                    "notify_marketing",
                    models.BooleanField(default=False, help_text="Receive marketing emails"),
                ),
                (
                    "notify_event_updates",
                    models.BooleanField(default=True, help_text="Receive event change notifications"),
                ),
                (
                    "organizer_bio",
                    models.TextField(
                        blank=True,
                        help_text="Public bio for organizer profile",
                        max_length=2000,
                    ),
                ),
                (
                    "organizer_website",
                    models.URLField(blank=True, help_text="Website URL"),
                ),
                (
                    "organizer_linkedin",
                    models.URLField(blank=True, help_text="LinkedIn profile URL"),
                ),
                (
                    "organizer_twitter",
                    models.CharField(blank=True, help_text="Twitter/X handle", max_length=100),
                ),
                (
                    "organizer_logo_url",
                    models.URLField(blank=True, help_text="Organization logo URL"),
                ),
                (
                    "organizer_slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier for public profile",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "events_attended_count",
                    models.PositiveIntegerField(default=0, help_text="Number of events attended"),
                ),
                (
                    "certificates_earned_count",
                    models.PositiveIntegerField(default=0, help_text="Number of certificates earned"),
                ),
                (
                    "total_cpd_credits",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total CPD credits earned",
                        max_digits=8,
                    ),
                ),
                (
                    "events_hosted_count",
                    models.PositiveIntegerField(default=0, help_text="Number of events hosted"),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(blank=True, help_text="Last successful login", null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="When this record was last modified"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public identifier for external use",
                        unique=True,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True,
                        help_text="Django session key",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, help_text="IP address", null=True),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="Browser user agent"),
                ),
                (
                    "device_type",
                    models.CharField(blank=True, help_text="Detected device type", max_length=50),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(auto_now=True, help_text="Last activity timestamp"),
                ),
                ("expires_at", models.DateTimeField(help_text="When session expires")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether session is active"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "db_table": "user_sessions",
                "ordering": ["-last_activity_at"],
            },
        ),
        migrations.CreateModel(
            name="ZoomConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="When this record was last modified"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public identifier for external use",
                        unique=True,
                    ),
                ),
                (
                    "access_token",
                    common.fields.EncryptedTextField(help_text="Zoom OAuth access token"),
                ),
                (
                    "refresh_token",
                    common.fields.EncryptedTextField(help_text="Zoom OAuth refresh token"),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(help_text="When access token expires"),
                ),
                (
                    "zoom_user_id",
                    models.CharField(help_text="Zoom user ID", max_length=100),
                ),
                (
                    "zoom_account_id",
                    models.CharField(blank=True, help_text="Zoom account ID", max_length=100),
                ),
                (
                    "zoom_email",
                    common.fields.LowercaseEmailField(
                        blank=True,
                        help_text="Email associated with Zoom account",
                        max_length=254,
                    ),
                ),
                (
                    "scopes",
                    models.TextField(blank=True, help_text="OAuth scopes granted (comma-separated)"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether connection is active"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, help_text="Last time connection was used", null=True),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, help_text="Last error message (if any)"),
                ),
                (
                    "last_error_at",
                    models.DateTimeField(blank=True, help_text="When last error occurred", null=True),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(default=0, help_text="Consecutive error count"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zoom_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zoom Connection",
                "verbose_name_plural": "Zoom Connections",
                "db_table": "zoom_connections",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["account_type"], name="users_account_e502f1_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["uuid"], name="users_uuid_4cb658_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["organizer_slug"], name="users_organiz_9d78e5_idx"),
        ),
    ]
