# Generated by Django 6.0.3 on 2026-04-12 00:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='last_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the invitation was last sent'),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='resent_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times this invitation has been resent'),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='revoked_at',
            field=models.DateTimeField(blank=True, help_text='When the invitation was revoked by an admin', null=True),
        ),
    ]
