# Generated by Django 6.0 on 2026-01-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpdrequirement',
            options={'ordering': ['-created_at'], 'verbose_name': 'CPD Requirement', 'verbose_name_plural': 'CPD Requirements'},
        ),
    ]
