# Generated by Django 6.0 on 2026-01-19 22:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('certificates', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPDTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                (
                    'transaction_type',
                    models.CharField(
                        choices=[
                            ('earned', 'Earned'),
                            ('manual_adjustment', 'Manual Adjustment'),
                            ('expired', 'Expired'),
                            ('revoked', 'Revoked'),
                        ],
                        default='earned',
                        help_text='Type of CPD credit transaction',
                        max_length=30,
                    ),
                ),
                (
                    'credits',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='Credit amount (positive for earned, negative for revoked/expired)',
                        max_digits=8,
                    ),
                ),
                (
                    'balance_after',
                    models.DecimalField(
                        decimal_places=2, help_text="User's total CPD balance after this transaction", max_digits=8
                    ),
                ),
                ('notes', models.TextField(blank=True, help_text='Additional notes or reason for transaction')),
                ('cpd_type', models.CharField(blank=True, help_text='CPD type code (if applicable)', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction metadata')),
                (
                    'certificate',
                    models.ForeignKey(
                        blank=True,
                        help_text='Associated certificate (for earned credits)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='cpd_transactions',
                        to='certificates.certificate',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        help_text='Admin user who created manual transaction',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='cpd_transactions_created',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cpd_transactions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'CPD Transaction',
                'verbose_name_plural': 'CPD Transactions',
                'db_table': 'cpd_transactions',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', '-created_at'], name='cpd_transac_user_id_a6d25d_idx'),
                    models.Index(fields=['transaction_type'], name='cpd_transac_transac_9b6fda_idx'),
                    models.Index(fields=['certificate'], name='cpd_transac_certifi_6d3696_idx'),
                ],
            },
        ),
    ]
