# Generated by Django 6.0 on 2025-12-17 03:06

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPDRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Public identifier for external use',
                        unique=True,
                    ),
                ),
                (
                    'cpd_type',
                    models.CharField(help_text="CPD type code (e.g., 'general', 'clinical', 'ethics')", max_length=100),
                ),
                ('cpd_type_display', models.CharField(blank=True, help_text='Human-readable CPD type name', max_length=255)),
                (
                    'annual_requirement',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='Required credits per period',
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    'period_type',
                    models.CharField(
                        choices=[
                            ('calendar_year', 'Calendar Year (Jan-Dec)'),
                            ('fiscal_year', 'Fiscal Year'),
                            ('rolling_12', 'Rolling 12 Months'),
                        ],
                        default='calendar_year',
                        max_length=20,
                    ),
                ),
                (
                    'fiscal_year_start_month',
                    models.PositiveSmallIntegerField(default=1, help_text='Month when fiscal year starts (1-12)'),
                ),
                ('fiscal_year_start_day', models.PositiveSmallIntegerField(default=1, help_text='Day when fiscal year starts')),
                ('licensing_body', models.CharField(blank=True, help_text='Name of licensing body', max_length=255)),
                ('license_number', models.CharField(blank=True, help_text='License number', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this requirement')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this requirement is active')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cpd_requirements',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'CPD Requirement',
                'verbose_name_plural': 'CPD Requirements',
                'db_table': 'cpd_requirements',
                'indexes': [models.Index(fields=['user', 'is_active'], name='cpd_require_user_id_58ae84_idx')],
                'unique_together': {('user', 'cpd_type')},
            },
        ),
    ]
