# Generated by Django 6.0 on 2026-01-22 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpdtransaction',
            name='certificate',
            field=models.ForeignKey(
                blank=True,
                help_text='Associated certificate (for earned credits)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cpd_transactions',
                to='certificates.certificate',
            ),
        ),
        migrations.AddField(
            model_name='cpdtransaction',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                help_text='Admin user who created manual transaction',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cpd_transactions_created',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='cpdtransaction',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='cpd_transactions', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='zoomconnection',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='zoom_connection', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['uuid'], name='users_uuid_4cb658_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organizer_slug'], name='users_organiz_9d78e5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'action'], name='audit_logs_actor_i_cf1ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action'], name='audit_logs_user_id_d685f3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='audit_logs_created_43fcd6_idx'),
        ),
        migrations.AddIndex(
            model_name='cpdrequirement',
            index=models.Index(fields=['user', 'is_active'], name='cpd_require_user_id_58ae84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cpdrequirement',
            unique_together={('user', 'cpd_type')},
        ),
        migrations.AddIndex(
            model_name='cpdtransaction',
            index=models.Index(fields=['user', '-created_at'], name='cpd_transac_user_id_a6d25d_idx'),
        ),
        migrations.AddIndex(
            model_name='cpdtransaction',
            index=models.Index(fields=['transaction_type'], name='cpd_transac_transac_9b6fda_idx'),
        ),
        migrations.AddIndex(
            model_name='cpdtransaction',
            index=models.Index(fields=['certificate'], name='cpd_transac_certifi_6d3696_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_63f199_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at'], name='notificatio_user_id_6c7360_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='notificatio_created_8fa075_idx'),
        ),
    ]
