# Generated by Django 6.0.3 on 2026-04-28 02:57

import common.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0002_initial'),
        ('events', '0002_initial'),
        ('learning', '0002_alter_courseenrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('target_type', models.CharField(choices=[('event', 'Event'), ('course', 'Course')], db_index=True, max_length=10)),
                ('email', common.fields.LowercaseEmailField(db_index=True, help_text='Invitee email (canonical, lowercase)', max_length=254)),
                ('full_name', models.CharField(blank=True, help_text='Snapshot at invite time', max_length=255)),
                ('personal_message', models.TextField(blank=True, max_length=1000)),
                ('comp', models.BooleanField(default=False, help_text='If True and target is paid, accept creates a free comp seat instead of routing to checkout')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_count', models.PositiveIntegerField(default=0)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_invitations_accepted', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, help_text="Linked Contact (if invitee was picked from organizer's contacts)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_invitations', to='contacts.contact')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_invitations', to='learning.course')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_invitations', to='events.event')),
                ('invited_by', models.ForeignKey(help_text='Organizer / instructor / admin who sent the invite', on_delete=django.db.models.deletion.PROTECT, related_name='learning_invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Invitation',
                'verbose_name_plural': 'Learning Invitations',
                'db_table': 'learning_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='learning_in_event_i_582df1_idx'), models.Index(fields=['course', 'status'], name='learning_in_course__a012c5_idx'), models.Index(fields=['email'], name='learning_in_email_cbe4f4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', True), ('event__isnull', False)), models.Q(('course__isnull', False), ('event__isnull', True)), _connector='OR'), name='learning_invitation_one_target'), models.UniqueConstraint(condition=models.Q(('event__isnull', False), ('status', 'pending')), fields=('event', 'email'), name='one_pending_event_invite_per_email'), models.UniqueConstraint(condition=models.Q(('course__isnull', False), ('status', 'pending')), fields=('course', 'email'), name='one_pending_course_invite_per_email')],
            },
        ),
    ]
