# Generated by Django 6.0.3 on 2026-04-12 01:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinvitation_last_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('from_roles', models.JSONField(default=list)),
                ('to_roles', models.JSONField(default=list)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_role_changes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_role_c_user_id_51eb49_idx'), models.Index(fields=['changed_by', '-created_at'], name='user_role_c_changed_765d03_idx')],
            },
        ),
    ]
