# Generated by Django 6.0.3 on 2026-04-28 17:14

import common.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_learninginvitation'),
        ('registrations', '0002_registration_comped_by_registration_was_comped'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier for external use', unique=True)),
                ('purpose', models.CharField(choices=[('registration_claim', 'Registration claim'), ('sign_in', 'Email sign-in')], db_index=True, max_length=32)),
                ('email', common.fields.LowercaseEmailField(db_index=True, help_text='Recipient (canonical, lowercase)', max_length=254)),
                ('token', models.CharField(db_index=True, help_text='Random secret stored once. Signed via TimestampSigner on render.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_count', models.PositiveIntegerField(default=0)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magic_links_accepted', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(blank=True, help_text='REGISTRATION_CLAIM only. Audit / idempotency — access is via email match.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to='registrations.registration')),
            ],
            options={
                'verbose_name': 'Magic Link',
                'verbose_name_plural': 'Magic Links',
                'db_table': 'magic_links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'status'], name='magic_links_email_199f7a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('purpose', 'registration_claim'), ('status', 'pending')), fields=('registration',), name='one_pending_claim_per_registration')],
            },
        ),
    ]
