# Generated by Django 6.0 on 2025-12-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cpdrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile image file', null=True, upload_to='profile_images/'),
        ),
    ]
