# Generated by Django 6.0 on 2025-12-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='User bio/description', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='is_organizer_profile_public',
            field=models.BooleanField(default=False, help_text='Make organizer profile visible to public'),
        ),
    ]
