# Generated by Django 6.0.3 on 2026-04-12 01:16

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_migrate_is_staff_to_admin_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_change_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the email change was requested', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_change_token',
            field=models.CharField(blank=True, help_text='Token for confirming email change', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=common.fields.LowercaseEmailField(blank=True, help_text='New email awaiting confirmation', max_length=254),
        ),
    ]
