# Generated by Django 6.0.3 on 2026-04-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_change_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvitation',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('educator', 'Educator'), ('course_manager', 'Course Manager'), ('instructor', 'Instructor'), ('admin', 'Admin')], default='learner', help_text='Role to assign on acceptance', max_length=20),
        ),
    ]
