# Generated by Django 6.0 on 2026-01-12 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_audit_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_actor_i_cf1ffa_idx',
            old_name='audit_logs_actor__0e0c88_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_organiz_9c5b7f_idx',
            old_name='audit_logs_organi_5f4f62_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_created_43fcd6_idx',
            old_name='audit_logs_created_d9bb4c_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_63f199_idx',
            old_name='notifications_user_n_1d3c7d_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_6c7360_idx',
            old_name='notifications_user_r_0f6b4a_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_created_8fa075_idx',
            old_name='notifications_created_1b2e7f_idx',
        ),
    ]
