# Generated by Django 6.0.3 on 2026-04-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userinvitation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_failed', 'Payment Failed'), ('refund_processed', 'Refund Processed'), ('invitation_sent', 'Invitation Sent'), ('account_activated', 'Account Activated'), ('discussion_reply', 'Discussion Reply'), ('discussion_mention', 'Discussion Mention'), ('discussion_flag_resolved', 'Discussion Flag Resolved'), ('system', 'System')], db_index=True, default='system', max_length=50),
        ),
    ]
