# Generated by Django 6.0 on 2026-01-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_audit_logs_actor__0e0c88_idx_audit_logs_actor_i_cf1ffa_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether user completed initial onboarding'),
        ),
    ]
