# Generated by Django 6.0.3 on 2026-04-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvitation',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('organizer', 'Organizer'), ('instructor', 'Instructor'), ('admin', 'Admin')], default='learner', help_text='Role to assign on acceptance', max_length=20),
        ),
    ]
