# Generated by Django 6.0.3 on 2026-04-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userinvitation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Customer id (cus_...); created on first checkout', max_length=64, null=True, unique=True),
        ),
    ]
