# Generated by Django 6.0 on 2026-01-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(
                choices=[('local', 'Local'), ('google', 'Google'), ('zoom', 'Zoom')],
                default='local',
                help_text='Original authentication method used for account creation',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='google_user_id',
            field=models.CharField(
                blank=True, db_index=True, help_text='Google user ID for OAuth', max_length=255, null=True, unique=True
            ),
        ),
    ]
