# Generated by Django 6.0.3 on 2026-04-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, db_index=True, help_text='Firebase UID; set on first successful Firebase-backed sign-in (e.g., Google).', max_length=128, null=True, unique=True),
        ),
    ]
