# Generated by Django 6.0.3 on 2026-04-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_badges',
            field=models.BooleanField(default=True, help_text='Receive badge notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_course_progress',
            field=models.BooleanField(default=True, help_text='Receive course progress notifications (enrollment, module release, completion)'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_recordings',
            field=models.BooleanField(default=True, help_text='Receive notifications when event recordings are published'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_failed', 'Payment Failed'), ('refund_processed', 'Refund Processed'), ('invitation_sent', 'Invitation Sent'), ('account_activated', 'Account Activated'), ('discussion_reply', 'Discussion Reply'), ('discussion_mention', 'Discussion Mention'), ('discussion_flag_resolved', 'Discussion Flag Resolved'), ('event_reminder_24h', 'Event Reminder (24h)'), ('event_starting_soon', 'Event Starting Soon'), ('event_cancelled', 'Event Cancelled'), ('event_rescheduled', 'Event Rescheduled'), ('waitlist_promoted', 'Waitlist Promoted'), ('recording_available', 'Recording Available'), ('certificate_issued', 'Certificate Issued'), ('badge_issued', 'Badge Issued'), ('course_enrolled', 'Course Enrolled'), ('module_released', 'Module Released'), ('course_completed', 'Course Completed'), ('system', 'System')], db_index=True, default='system', max_length=50),
        ),
    ]
